// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

export class CompatTimeline {
    /**
     * Creates a new CompatTimeline instance.
     * @param {Partial<CompatTimeline>} [$$source = {}] - The source object to create the CompatTimeline.
     */
    constructor($$source = {}) {
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("asset_paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["asset_paths"] = [];
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_id"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("author_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author_id"] = "";
        }
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {models$0.CheckpointGroupTag[]}
             */
            this["tags"] = [];
        }
        if (!("follower_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["follower_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompatTimeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompatTimeline}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $Create.ByteSlice;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("asset_paths" in $$parsedSource) {
            $$parsedSource["asset_paths"] = $$createField1_0($$parsedSource["asset_paths"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField6_0($$parsedSource["preview"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new CompatTimeline(/** @type {Partial<CompatTimeline>} */($$parsedSource));
    }
}

export class PreLaunchEnvironmentVariable {
    /**
     * Creates a new PreLaunchEnvironmentVariable instance.
     * @param {Partial<PreLaunchEnvironmentVariable>} [$$source = {}] - The source object to create the PreLaunchEnvironmentVariable.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreLaunchEnvironmentVariable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreLaunchEnvironmentVariable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreLaunchEnvironmentVariable(/** @type {Partial<PreLaunchEnvironmentVariable>} */($$parsedSource));
    }
}

export class PreLaunchHook {
    /**
     * Creates a new PreLaunchHook instance.
     * @param {Partial<PreLaunchHook>} [$$source = {}] - The source object to create the PreLaunchHook.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }
        if (!("application_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["application_version"] = "";
        }
        if (!("script_asset_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["script_asset_ids"] = [];
        }
        if (!("environment_variable_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["environment_variable_ids"] = [];
        }
        if (!("failure_policy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["failure_policy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreLaunchHook instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreLaunchHook}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        if ("script_asset_ids" in $$parsedSource) {
            $$parsedSource["script_asset_ids"] = $$createField5_0($$parsedSource["script_asset_ids"]);
        }
        if ("environment_variable_ids" in $$parsedSource) {
            $$parsedSource["environment_variable_ids"] = $$createField6_0($$parsedSource["environment_variable_ids"]);
        }
        return new PreLaunchHook(/** @type {Partial<PreLaunchHook>} */($$parsedSource));
    }
}

export class PreLaunchHookSettings {
    /**
     * Creates a new PreLaunchHookSettings instance.
     * @param {Partial<PreLaunchHookSettings>} [$$source = {}] - The source object to create the PreLaunchHookSettings.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("environment_variables" in $$source)) {
            /**
             * @member
             * @type {PreLaunchEnvironmentVariable[]}
             */
            this["environment_variables"] = [];
        }
        if (!("hooks" in $$source)) {
            /**
             * @member
             * @type {PreLaunchHook[]}
             */
            this["hooks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreLaunchHookSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreLaunchHookSettings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environment_variables" in $$parsedSource) {
            $$parsedSource["environment_variables"] = $$createField1_0($$parsedSource["environment_variables"]);
        }
        if ("hooks" in $$parsedSource) {
            $$parsedSource["hooks"] = $$createField2_0($$parsedSource["hooks"]);
        }
        return new PreLaunchHookSettings(/** @type {Partial<PreLaunchHookSettings>} */($$parsedSource));
    }
}

export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sync_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sync_token"] = "";
        }
        if (!("preview_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uri"] = "";
        }
        if (!("working_directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["working_directory"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["location_id"] = undefined;
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("has_remote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_remote"] = false;
        }
        if (!("is_unsynced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_unsynced"] = false;
        }
        if (!("is_downloaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_downloaded"] = false;
        }
        if (!("is_closed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_closed"] = false;
        }
        if (!("is_outdated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_outdated"] = false;
        }
        if (!("is_tracked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_tracked"] = false;
        }
        if (!("is_offline" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_offline"] = false;
        }
        if (!("ignore_list" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ignore_list"] = [];
        }
        if (!("storage_mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storage_mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["role"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["owner_name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        const $$createField19_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignore_list" in $$parsedSource) {
            $$parsedSource["ignore_list"] = $$createField19_0($$parsedSource["ignore_list"]);
        }
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

export class ProjectScriptSettings {
    /**
     * Creates a new ProjectScriptSettings instance.
     * @param {Partial<ProjectScriptSettings>} [$$source = {}] - The source object to create the ProjectScriptSettings.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectScriptSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectScriptSettings}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        return new ProjectScriptSettings(/** @type {Partial<ProjectScriptSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.CheckpointGroupTag.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PreLaunchEnvironmentVariable.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = PreLaunchHook.createFrom;
const $$createType6 = $Create.Array($$createType5);
