// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChangeSummary groups all pending changes by category for frontend display.
 */
export class ChangeSummary {
    /**
     * Creates a new ChangeSummary instance.
     * @param {Partial<ChangeSummary>} [$$source = {}] - The source object to create the ChangeSummary.
     */
    constructor($$source = {}) {
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {ChangeSummaryItem[]}
             */
            this["assets"] = [];
        }
        if (!("collections" in $$source)) {
            /**
             * @member
             * @type {ChangeSummaryItem[]}
             */
            this["collections"] = [];
        }
        if (!("other" in $$source)) {
            /**
             * @member
             * @type {ChangeSummaryItem[]}
             */
            this["other"] = [];
        }
        if (!("total_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangeSummary}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField0_0($$parsedSource["assets"]);
        }
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField1_0($$parsedSource["collections"]);
        }
        if ("other" in $$parsedSource) {
            $$parsedSource["other"] = $$createField2_0($$parsedSource["other"]);
        }
        return new ChangeSummary(/** @type {Partial<ChangeSummary>} */($$parsedSource));
    }
}

/**
 * ChangeSummaryItem represents a single unsynced change for the changelog UI.
 */
export class ChangeSummaryItem {
    /**
     * Creates a new ChangeSummaryItem instance.
     * @param {Partial<ChangeSummaryItem>} [$$source = {}] - The source object to create the ChangeSummaryItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("change_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["change_type"] = "";
        }
        if (!("mtime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mtime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeSummaryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangeSummaryItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangeSummaryItem(/** @type {Partial<ChangeSummaryItem>} */($$parsedSource));
    }
}

export class SyncOptions {
    /**
     * Creates a new SyncOptions instance.
     * @param {Partial<SyncOptions>} [$$source = {}] - The source object to create the SyncOptions.
     */
    constructor($$source = {}) {
        if (!("only_latest_checkpoints" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["only_latest_checkpoints"] = false;
        }
        if (!("asset_dependencies" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["asset_dependencies"] = false;
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["assets"] = false;
        }
        if (!("resources" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resources"] = false;
        }
        if (!("templates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["templates"] = false;
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncOptions(/** @type {Partial<SyncOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ChangeSummaryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
