// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class SyncOptions {
    /**
     * Creates a new SyncOptions instance.
     * @param {Partial<SyncOptions>} [$$source = {}] - The source object to create the SyncOptions.
     */
    constructor($$source = {}) {
        if (!("only_latest_checkpoints" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["only_latest_checkpoints"] = false;
        }
        if (!("task_dependencies" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["task_dependencies"] = false;
        }
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tasks"] = false;
        }
        if (!("resources" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resources"] = false;
        }
        if (!("templates" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["templates"] = false;
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncOptions(/** @type {Partial<SyncOptions>} */($$parsedSource));
    }
}
