// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * StudioInfo represents metadata returned by a studio server's /studio-info endpoint
 */
export class StudioInfo {
    /**
     * Creates a new StudioInfo instance.
     * @param {Partial<StudioInfo>} [$$source = {}] - The source object to create the StudioInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("alt_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alt_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudioInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StudioInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudioInfo(/** @type {Partial<StudioInfo>} */($$parsedSource));
    }
}
