// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ScriptReference {
    /**
     * Creates a new ScriptReference instance.
     * @param {Partial<ScriptReference>} [$$source = {}] - The source object to create the ScriptReference.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }
        if (!("tracked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tracked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptReference instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptReference}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptReference(/** @type {Partial<ScriptReference>} */($$parsedSource));
    }
}
