// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Asset {
    /**
     * Creates a new Asset instance.
     * @param {Partial<Asset>} [$$source = {}] - The source object to create the Asset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }
        if (!("collection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collection_id"] = "";
        }
        if (!("collection_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collection_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Asset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset(/** @type {Partial<Asset>} */($$parsedSource));
    }
}

export class Collection {
    /**
     * Creates a new Collection instance.
     * @param {Partial<Collection>} [$$source = {}] - The source object to create the Collection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("collection_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collection_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collection(/** @type {Partial<Collection>} */($$parsedSource));
    }
}

export class Operation {
    /**
     * Creates a new Operation instance.
     * @param {Partial<Operation>} [$$source = {}] - The source object to create the Operation.
     */
    constructor($$source = {}) {
        if (!("operation_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation_id"] = "";
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_id"] = "";
        }
        if (!("project_uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_uri"] = "";
        }
        if (!("project_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("cancel_requested" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancel_requested"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("extra_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extra_message"] = "";
        }
        if (!("download_message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_message"] = "";
        }
        if (!("percentage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percentage"] = 0;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {Asset[]}
             */
            this["assets"] = [];
        }
        if (!("collections" in $$source)) {
            /**
             * @member
             * @type {Collection[]}
             */
            this["collections"] = [];
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("restored_asset_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["restored_asset_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Operation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Operation}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType3;
        const $$createField17_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField14_0($$parsedSource["assets"]);
        }
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField15_0($$parsedSource["collections"]);
        }
        if ("restored_asset_ids" in $$parsedSource) {
            $$parsedSource["restored_asset_ids"] = $$createField17_0($$parsedSource["restored_asset_ids"]);
        }
        return new Operation(/** @type {Partial<Operation>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("operations" in $$source)) {
            /**
             * @member
             * @type {Operation[]}
             */
            this["operations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField1_0($$parsedSource["operations"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Collection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Operation.createFrom;
const $$createType6 = $Create.Array($$createType5);
