// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../server/models/models.js";

/**
 * LocationHealth represents the health status of a location
 */
export class LocationHealth {
    /**
     * Creates a new LocationHealth instance.
     * @param {Partial<LocationHealth>} [$$source = {}] - The source object to create the LocationHealth.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("writable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["writable"] = false;
        }
        if (!("free_space" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["free_space"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocationHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationHealth(/** @type {Partial<LocationHealth>} */($$parsedSource));
    }
}

export class ProjectLocation {
    /**
     * Creates a new ProjectLocation instance.
     * @param {Partial<ProjectLocation>} [$$source = {}] - The source object to create the ProjectLocation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bookmark"] = "";
        }
        if (!("is_default" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_default"] = false;
        }
        if (!("project_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["project_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectLocation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectLocation}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $Create.ByteSlice;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bookmark" in $$parsedSource) {
            $$parsedSource["bookmark"] = $$createField3_0($$parsedSource["bookmark"]);
        }
        if ("project_ids" in $$parsedSource) {
            $$parsedSource["project_ids"] = $$createField5_0($$parsedSource["project_ids"]);
        }
        return new ProjectLocation(/** @type {Partial<ProjectLocation>} */($$parsedSource));
    }
}

export class Studio {
    /**
     * Creates a new Studio instance.
     * @param {Partial<Studio>} [$$source = {}] - The source object to create the Studio.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["active"] = "";
        }
        if (!("alt_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alt_url"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usage"] = "";
        }
        if (!("Users" in $$source)) {
            /**
             * @member
             * @type {models$0.StudioUserInfo[]}
             */
            this["Users"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Studio instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Studio}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Users" in $$parsedSource) {
            $$parsedSource["Users"] = $$createField6_0($$parsedSource["Users"]);
        }
        return new Studio(/** @type {Partial<Studio>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.StudioUserInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
