// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the AI agent to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../internal/agent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToolCall responds to an agent-tool-approval-request from the frontend.
 * Pass approved=true to allow the checked items to run, false to deny it.
 * Safe to call with an unknown ID (returns nil).
 * @param {string} toolCallID
 * @param {boolean} approved
 * @param {string[]} selectedKeys
 * @returns {$CancellablePromise<void>}
 */
export function ApproveToolCall(toolCallID, approved, selectedKeys) {
    return $Call.ByID(3865245129, toolCallID, approved, selectedKeys);
}

/**
 * CancelRun cancels an in-flight agent run for the given project.
 * Safe to call when no run is active (returns nil).
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function CancelRun(projectPath) {
    return $Call.ByID(259069029, projectPath);
}

/**
 * ClearChatSession clears the conversation history for a project.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatSession(projectPath) {
    return $Call.ByID(186816551, projectPath);
}

/**
 * DeleteChatTurn removes a user request and its associated response.
 * @param {string} projectPath
 * @param {number} turnIndex
 * @returns {$CancellablePromise<void>}
 */
export function DeleteChatTurn(projectPath, turnIndex) {
    return $Call.ByID(3839363736, projectPath, turnIndex);
}

/**
 * GetAPIKeyStatus checks if an API key is configured. Never returns the key itself.
 * @returns {$CancellablePromise<$models.AgentKeyStatus>}
 */
export function GetAPIKeyStatus() {
    return $Call.ByID(3392167155).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAutoApproveDestructive reports whether destructive tool calls auto-execute
 * without prompting the user.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoApproveDestructive() {
    return $Call.ByID(1080847226);
}

/**
 * GetAvailableModels returns the list of selectable models for the given provider.
 * The first entry is the provider's default. Empty slice for unknown providers.
 * @param {string} provider
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableModels(provider) {
    return $Call.ByID(3320819787, provider).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetChatHistory returns the persisted conversation history mapped to UI message types.
 * Tool-calling assistant messages are grouped by tool name.
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.ChatUIMessage[]>}
 */
export function GetChatHistory(projectPath) {
    return $Call.ByID(4191745416, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSelectedModel returns the user-selected model for the provider, or the
 * provider default if no override has been set.
 * @param {string} provider
 * @returns {$CancellablePromise<string>}
 */
export function GetSelectedModel(provider) {
    return $Call.ByID(3586811348, provider);
}

/**
 * @param {string} projectPath
 * @param {string} parentID
 * @returns {$CancellablePromise<agent$0.EntityReference[]>}
 */
export function ListEntityReferenceChildren(projectPath, parentID) {
    return $Call.ByID(4012408445, projectPath, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<agent$0.ScriptReference[]>}
 */
export function ListScriptReferences(projectPath) {
    return $Call.ByID(1114395811, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * RemoveAPIKey deletes the stored API key.
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAPIKey() {
    return $Call.ByID(668385785);
}

/**
 * RetryLastTurn cancels any running agent execution, deletes the last user message and subsequent assistant messages/errors, and restarts the run.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function RetryLastTurn(projectPath) {
    return $Call.ByID(3928494511, projectPath);
}

/**
 * SendMessage sends a user message to the agent, which calls the LLM and executes tools.
 * Results are streamed back via Wails events: agent-status, agent-tool-start, agent-tool-result, agent-response, agent-error.
 * @param {string} projectPath
 * @param {string} message
 * @param {string} displayMessage
 * @param {string} attachmentPath
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(projectPath, message, displayMessage, attachmentPath) {
    return $Call.ByID(3870210951, projectPath, message, displayMessage, attachmentPath);
}

/**
 * SetAPIKey stores the user's LLM API key in settings.
 * Provider should be "openai", "anthropic", "gemini", "groq", or "ollama".
 * @param {string} provider
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIKey(provider, apiKey) {
    return $Call.ByID(3427571309, provider, apiKey);
}

/**
 * SetAutoApproveDestructive persists the auto-approve preference.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoApproveDestructive(enabled) {
    return $Call.ByID(3546589254, enabled);
}

/**
 * SetSelectedModel persists the chosen model for the given provider.
 * Passing an empty model clears the override and reverts to the provider default.
 * @param {string} provider
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetSelectedModel(provider, model) {
    return $Call.ByID(557898616, provider, model);
}

// Private type creation functions
const $$createType0 = $models.AgentKeyStatus.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.ChatUIMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = agent$0.EntityReference.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = agent$0.ScriptReference.createFrom;
const $$createType7 = $Create.Array($$createType6);
