// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} dependencyId
 * @param {string} dependencyTypeId
 * @returns {$CancellablePromise<models$0.TaskDependency>}
 */
export function AddAssetDependency(projectPath, taskId, dependencyId, dependencyTypeId) {
    return $Call.ByID(1782495003, projectPath, taskId, dependencyId, dependencyTypeId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * dependencies
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} dependencyId
 * @param {string} dependencyTypeId
 * @returns {$CancellablePromise<models$0.TaskDependency>}
 */
export function AddEntityDependency(projectPath, taskId, dependencyId, dependencyTypeId) {
    return $Call.ByID(4021458000, projectPath, taskId, dependencyId, dependencyTypeId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} previewPath
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function AddPreview(projectPath, taskId, previewPath) {
    return $Call.ByID(3759703590, projectPath, taskId, previewPath);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @returns {$CancellablePromise<string>}
 */
export function AssetFileStatus(projectPath, taskId) {
    return $Call.ByID(1128980665, projectPath, taskId);
}

/**
 * @param {string} projectPath
 * @param {string[]} taskIds
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function AssetFilesStatus(projectPath, taskIds) {
    return $Call.ByID(3141819454, projectPath, taskIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} userId
 * @returns {$CancellablePromise<void>}
 */
export function AssignAsset(projectPath, taskId, userId) {
    return $Call.ByID(1650043410, projectPath, taskId, userId);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} entityId
 * @returns {$CancellablePromise<void>}
 */
export function ChangeAssetCollection(projectPath, taskId, entityId) {
    return $Call.ByID(1344461689, projectPath, taskId, entityId);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} taskTypeId
 * @returns {$CancellablePromise<void>}
 */
export function ChangeAssetType(projectPath, taskId, taskTypeId) {
    return $Call.ByID(568329317, projectPath, taskId, taskTypeId);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} statusId
 * @returns {$CancellablePromise<void>}
 */
export function ChangeStatus(projectPath, taskId, statusId) {
    return $Call.ByID(2581918589, projectPath, taskId, statusId);
}

/**
 * @param {string} projectPath
 * @param {string} name
 * @param {string} description
 * @param {string} taskTypeId
 * @param {string} entityId
 * @param {boolean} isResource
 * @param {string} templateId
 * @param {string} templateFilePath
 * @param {string} pointer
 * @param {boolean} isLink
 * @param {string[]} tags
 * @param {string} previewPath
 * @param {string} comment
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function CreateAsset(projectPath, name, description, taskTypeId, entityId, isResource, templateId, templateFilePath, pointer, isLink, tags, previewPath, comment) {
    return $Call.ByID(3537301857, projectPath, name, description, taskTypeId, entityId, isResource, templateId, templateFilePath, pointer, isLink, tags, previewPath, comment);
}

/**
 * @param {string} projectPath
 * @param {string} name
 * @param {string} icon
 * @returns {$CancellablePromise<models$0.TaskType>}
 */
export function CreateAssetType(projectPath, name, icon) {
    return $Call.ByID(2315337865, projectPath, name, icon).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {boolean} removeFiles
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAsset(projectPath, taskId, removeFiles) {
    return $Call.ByID(3374367108, projectPath, taskId, removeFiles);
}

/**
 * @param {string} projectPath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAssetType(projectPath, id) {
    return $Call.ByID(1866707372, projectPath, id);
}

/**
 * @param {string} projectPath
 * @param {string} sourceTaskId
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function DuplicateAsset(projectPath, sourceTaskId) {
    return $Call.ByID(301515392, projectPath, sourceTaskId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function GetAssetByID(projectPath, assetId) {
    return $Call.ByID(467161039, projectPath, assetId);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<number>}
 */
export function GetAssetCount(projectPath) {
    return $Call.ByID(4117607374, projectPath);
}

/**
 * @param {string} projectPath
 * @param {string[]} taskIds
 * @returns {$CancellablePromise<any[]>}
 */
export function GetAssetDependencies(projectPath, taskIds) {
    return $Call.ByID(2929165906, projectPath, taskIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string[]} taskIds
 * @returns {$CancellablePromise<models$0.Task[]>}
 */
export function GetAssetDependencies2(projectPath, taskIds) {
    return $Call.ByID(948472096, projectPath, taskIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @returns {$CancellablePromise<string>}
 */
export function GetAssetState(projectPath, taskId) {
    return $Call.ByID(1306124856, projectPath, taskId);
}

/**
 * GetAssetTasks gets all tasks where is_resource is false with minimal fields for UI display
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Task[]>}
 */
export function GetAssetTasks(projectPath) {
    return $Call.ByID(173054263, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * asset types
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.TaskType[]>}
 */
export function GetAssetTypes(projectPath) {
    return $Call.ByID(3278131604, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Task[]>}
 */
export function GetAssets(projectPath) {
    return $Call.ByID(4140153068, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function GetAssetsPB(projectPath) {
    return $Call.ByID(2358901634, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<$models.AssetsStates>}
 */
export function GetAssetsStates(projectPath, projectWorkingDir, ignoreList) {
    return $Call.ByID(4116784294, projectPath, projectWorkingDir, ignoreList).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {number} maxDepth
 * @returns {$CancellablePromise<any[]>}
 */
export function GetRecursiveDependencies(projectPath, taskId, maxDepth) {
    return $Call.ByID(2219419678, projectPath, taskId, maxDepth).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<string[]>}
 */
export function GetUntrackedFiles(projectPath, projectWorkingDir, ignoreList) {
    return $Call.ByID(1088682931, projectPath, projectWorkingDir, ignoreList).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} dependencyId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAssetDependency(projectPath, taskId, dependencyId) {
    return $Call.ByID(2690010132, projectPath, taskId, dependencyId);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} dependencyId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveEntityDependency(projectPath, taskId, dependencyId) {
    return $Call.ByID(2303119221, projectPath, taskId, dependencyId);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} name
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function RenameAsset(projectPath, taskId, name) {
    return $Call.ByID(2068335707, projectPath, taskId, name);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @returns {$CancellablePromise<void>}
 */
export function RevealAsset(projectPath, taskId) {
    return $Call.ByID(1172749270, projectPath, taskId);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function TestData() {
    return $Call.ByID(605945379);
}

/**
 * @param {string} projectPath
 * @param {string[]} taskIds
 * @param {boolean} isResource
 * @returns {$CancellablePromise<void>}
 */
export function ToggleIsResource(projectPath, taskIds, isResource) {
    return $Call.ByID(3235593635, projectPath, taskIds, isResource);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {boolean} isTask
 * @returns {$CancellablePromise<void>}
 */
export function ToggleIsTask(projectPath, taskId, isTask) {
    return $Call.ByID(1903957406, projectPath, taskId, isTask);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @returns {$CancellablePromise<void>}
 */
export function UnassignAsset(projectPath, taskId) {
    return $Call.ByID(2170415471, projectPath, taskId);
}

/**
 * @param {string} projectPath
 * @param {string[]} taskIds
 * @returns {$CancellablePromise<void>}
 */
export function UnassignAssets(projectPath, taskIds) {
    return $Call.ByID(3268802324, projectPath, taskIds);
}

/**
 * @param {string} projectPath
 * @param {string} taskId
 * @param {string} name
 * @param {string} taskTypeId
 * @param {boolean} isResource
 * @param {string} pointer
 * @param {string[]} tags
 * @returns {$CancellablePromise<models$0.Task>}
 */
export function UpdateAsset(projectPath, taskId, name, taskTypeId, isResource, pointer, tags) {
    return $Call.ByID(2839243450, projectPath, taskId, name, taskTypeId, isResource, pointer, tags);
}

/**
 * @param {string} projectPath
 * @param {string} id
 * @param {string} name
 * @param {string} icon
 * @returns {$CancellablePromise<models$0.TaskType>}
 */
export function UpdateAssetType(projectPath, id, name, icon) {
    return $Call.ByID(865399386, projectPath, id, name, icon).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.TaskDependency.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = models$0.TaskType.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType2);
const $$createType6 = $models.AssetsStates.createFrom;
const $$createType7 = $Create.Array($Create.Any);
