// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} dependencyId
 * @param {string} dependencyTypeId
 * @returns {$CancellablePromise<models$0.AssetDependencyEdge>}
 */
export function AddAssetDependency(projectPath, assetId, dependencyId, dependencyTypeId) {
    return $Call.ByID(1782495003, projectPath, assetId, dependencyId, dependencyTypeId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddAssetDependencyWithSelector creates a selector-aware dependency edge.
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} dependencyId
 * @param {string} dependencyTypeId
 * @param {string} resolutionMode
 * @param {string} checkpointId
 * @param {string} checkpointGroupTagId
 * @returns {$CancellablePromise<models$0.AssetDependencyEdge>}
 */
export function AddAssetDependencyWithSelector(projectPath, assetId, dependencyId, dependencyTypeId, resolutionMode, checkpointId, checkpointGroupTagId) {
    return $Call.ByID(1128916658, projectPath, assetId, dependencyId, dependencyTypeId, resolutionMode, checkpointId, checkpointGroupTagId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} dependencyId
 * @param {string} dependencyTypeId
 * @returns {$CancellablePromise<models$0.AssetDependency>}
 */
export function AddCollectionDependency(projectPath, assetId, dependencyId, dependencyTypeId) {
    return $Call.ByID(2670356863, projectPath, assetId, dependencyId, dependencyTypeId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} previewPath
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function AddPreview(projectPath, assetId, previewPath) {
    return $Call.ByID(3759703590, projectPath, assetId, previewPath);
}

/**
 * ApplyPathUpdate applies a pending remote path change to a local asset.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<void>}
 */
export function ApplyPathUpdate(projectPath, assetId) {
    return $Call.ByID(161235379, projectPath, assetId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<string>}
 */
export function AssetFileStatus(projectPath, assetId) {
    return $Call.ByID(1128980665, projectPath, assetId);
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function AssetFilesStatus(projectPath, assetIds) {
    return $Call.ByID(3141819454, projectPath, assetIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * AssignAsset assigns a asset to a user.
 * If the asset is a resource (is_resource == true), it will be converted to a asset first.
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} userId
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function AssignAsset(projectPath, assetId, userId) {
    return $Call.ByID(1650043410, projectPath, assetId, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AssignAssets assigns assets atomically; remote projects use one PATCH request.
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {string} userId
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function AssignAssets(projectPath, assetIds, userId) {
    return $Call.ByID(874985139, projectPath, assetIds, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<void>}
 */
export function AuthorizeCheckpoint(projectPath, assetIds) {
    return $Call.ByID(1869488836, projectPath, assetIds);
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<void>}
 */
export function AuthorizeRevert(projectPath, assetIds) {
    return $Call.ByID(163199156, projectPath, assetIds);
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {boolean} isTask
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function BulkToggleIsTask(projectPath, assetIds, isTask) {
    return $Call.ByID(938403102, projectPath, assetIds, isTask).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ChangeAssetCollection moves one or more assets to a different collection.
 * Checks for name+extension conflicts in the target collection before moving.
 * Returns an error if any asset would conflict or if the operation fails.
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {string} collectionId
 * @returns {$CancellablePromise<void>}
 */
export function ChangeAssetCollection(projectPath, assetIds, collectionId) {
    return $Call.ByID(1344461689, projectPath, assetIds, collectionId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} assetTypeId
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function ChangeAssetType(projectPath, assetId, assetTypeId) {
    return $Call.ByID(568329317, projectPath, assetId, assetTypeId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ChangeStatus updates asset statuses on the remote server first, then locally.
 * If no remote is configured, falls back to local-only update.
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {string} statusId
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function ChangeStatus(projectPath, assetIds, statusId) {
    return $Call.ByID(2581918589, projectPath, assetIds, statusId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CopyAssetToProject copies an asset from one project to another, including metadata, checkpoints, chunks, and previews.
 * If targetCollectionId is empty, the asset is copied to the root of the target project.
 * If copyAllCheckpoints is false, only the latest checkpoint is copied.
 * @param {string} sourceProjectPath
 * @param {string} sourceAssetId
 * @param {string} targetProjectPath
 * @param {string} targetCollectionId
 * @param {boolean} copyAllCheckpoints
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function CopyAssetToProject(sourceProjectPath, sourceAssetId, targetProjectPath, targetCollectionId, copyAllCheckpoints) {
    return $Call.ByID(1609902140, sourceProjectPath, sourceAssetId, targetProjectPath, targetCollectionId, copyAllCheckpoints);
}

/**
 * @param {string} projectPath
 * @param {string} name
 * @param {string} description
 * @param {string} assetTypeId
 * @param {string} collectionId
 * @param {boolean} isResource
 * @param {string} templateId
 * @param {string} templateFilePath
 * @param {string} pointer
 * @param {boolean} isLink
 * @param {string[]} tags
 * @param {string} previewPath
 * @param {string} comment
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function CreateAsset(projectPath, name, description, assetTypeId, collectionId, isResource, templateId, templateFilePath, pointer, isLink, tags, previewPath, comment) {
    return $Call.ByID(3537301857, projectPath, name, description, assetTypeId, collectionId, isResource, templateId, templateFilePath, pointer, isLink, tags, previewPath, comment);
}

/**
 * @param {string} projectPath
 * @param {string} name
 * @param {string} icon
 * @returns {$CancellablePromise<models$0.AssetType>}
 */
export function CreateAssetType(projectPath, name, icon) {
    return $Call.ByID(2315337865, projectPath, name, icon).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {boolean} removeFiles
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAsset(projectPath, assetId, removeFiles) {
    return $Call.ByID(3374367108, projectPath, assetId, removeFiles);
}

/**
 * @param {string} projectPath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAssetType(projectPath, id) {
    return $Call.ByID(1866707372, projectPath, id);
}

/**
 * DuplicateAsset duplicates a asset to the same or a different collection.
 * If targetCollectionId is empty, the asset is duplicated in the same collection as the source.
 * @param {string} projectPath
 * @param {string} sourceAssetId
 * @param {string} targetCollectionId
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function DuplicateAsset(projectPath, sourceAssetId, targetCollectionId) {
    return $Call.ByID(301515392, projectPath, sourceAssetId, targetCollectionId);
}

/**
 * GetAssetAssets gets all assets where is_resource is false with minimal fields for UI display
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetAssetAssets(projectPath) {
    return $Call.ByID(677448758, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function GetAssetByID(projectPath, assetId) {
    return $Call.ByID(467161039, projectPath, assetId);
}

/**
 * GetAssetByPath retrieves an asset by its asset_path and extension.
 * Returns the asset or an error if not found.
 * @param {string} projectPath
 * @param {string} assetPath
 * @param {string} extension
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function GetAssetByPath(projectPath, assetPath, extension) {
    return $Call.ByID(473301761, projectPath, assetPath, extension);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<number>}
 */
export function GetAssetCount(projectPath) {
    return $Call.ByID(4117607374, projectPath);
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<any[]>}
 */
export function GetAssetDependencies(projectPath, assetIds) {
    return $Call.ByID(2929165906, projectPath, assetIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetAssetDependencies2(projectPath, assetIds) {
    return $Call.ByID(948472096, projectPath, assetIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAssetDependencyEdges returns selector-aware dependency edges.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.AssetDependencyEdge[]>}
 */
export function GetAssetDependencyEdges(projectPath, assetId) {
    return $Call.ByID(2128218040, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<string>}
 */
export function GetAssetState(projectPath, assetId) {
    return $Call.ByID(1306124856, projectPath, assetId);
}

/**
 * asset types
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.AssetType[]>}
 */
export function GetAssetTypes(projectPath) {
    return $Call.ByID(3278131604, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetAssets(projectPath) {
    return $Call.ByID(4140153068, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function GetAssetsPB(projectPath) {
    return $Call.ByID(2358901634, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<$models.AssetsStates>}
 */
export function GetAssetsStates(projectPath, projectWorkingDir, ignoreList) {
    return $Call.ByID(4116784294, projectPath, projectWorkingDir, ignoreList).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetCollectionDescendantAssets returns assets located anywhere under the given collection's subtree.
 * includeResources controls whether resource assets are included alongside task assets.
 * @param {string} projectPath
 * @param {string} collectionId
 * @param {boolean} includeResources
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function GetCollectionDescendantAssets(projectPath, collectionId, includeResources) {
    return $Call.ByID(2603506523, projectPath, collectionId, includeResources).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetDependencySelectorOptions returns valid checkpoints and tags for an asset.
 * @param {string} projectPath
 * @param {string} dependencyId
 * @returns {$CancellablePromise<models$0.DependencySelectorOptions>}
 */
export function GetDependencySelectorOptions(projectPath, dependencyId) {
    return $Call.ByID(1756446805, projectPath, dependencyId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {number} maxDepth
 * @returns {$CancellablePromise<any[]>}
 */
export function GetRecursiveDependencies(projectPath, assetId, maxDepth) {
    return $Call.ByID(2219419678, projectPath, assetId, maxDepth).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetSiblingAssetNames returns the names of all assets in the same collection with the given extension.
 * Used for client-side name validation to avoid duplicate asset names.
 * @param {string} projectPath
 * @param {string} collectionId
 * @param {string} extension
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSiblingAssetNames(projectPath, collectionId, extension) {
    return $Call.ByID(3568231505, projectPath, collectionId, extension).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<string[]>}
 */
export function GetUntrackedFiles(projectPath, projectWorkingDir, ignoreList) {
    return $Call.ByID(1088682931, projectPath, projectWorkingDir, ignoreList).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * MoveAssetsToCollection moves one or more assets to a different collection.
 * Updates the database and moves the physical files if they exist on disk.
 * Checks for name+extension conflicts in the target collection before moving.
 * Returns an error if any asset would conflict or if the operation fails.
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {string} targetCollectionId
 * @returns {$CancellablePromise<void>}
 */
export function MoveAssetsToCollection(projectPath, assetIds, targetCollectionId) {
    return $Call.ByID(623994934, projectPath, assetIds, targetCollectionId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} dependencyId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAssetDependency(projectPath, assetId, dependencyId) {
    return $Call.ByID(2690010132, projectPath, assetId, dependencyId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} dependencyId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCollectionDependency(projectPath, assetId, dependencyId) {
    return $Call.ByID(2035690622, projectPath, assetId, dependencyId);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} name
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function RenameAsset(projectPath, assetId, name) {
    return $Call.ByID(2068335707, projectPath, assetId, name);
}

/**
 * ResolveBuildDependencies returns the asset and every asset transitively
 * reachable through its asset and collection dependencies. Used by the
 * "Build with dependencies" action to expand the full revert set on the
 * backend instead of relying on the partial frontend store.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<string[]>}
 */
export function ResolveBuildDependencies(projectPath, assetId) {
    return $Call.ByID(1805101810, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<void>}
 */
export function RevealAsset(projectPath, assetId) {
    return $Call.ByID(1172749270, projectPath, assetId);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function TestData() {
    return $Call.ByID(605945379);
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {boolean} isResource
 * @returns {$CancellablePromise<void>}
 */
export function ToggleIsResource(projectPath, assetIds, isResource) {
    return $Call.ByID(3235593635, projectPath, assetIds, isResource);
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {boolean} isTask
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function ToggleIsTask(projectPath, assetId, isTask) {
    return $Call.ByID(1903957406, projectPath, assetId, isTask).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function UnassignAsset(projectPath, assetId) {
    return $Call.ByID(2170415471, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<$models.MetadataUpdateResult>}
 */
export function UnassignAssets(projectPath, assetIds) {
    return $Call.ByID(3268802324, projectPath, assetIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} name
 * @param {string} assetTypeId
 * @param {boolean} isResource
 * @param {string} pointer
 * @param {string[]} tags
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function UpdateAsset(projectPath, assetId, name, assetTypeId, isResource, pointer, tags) {
    return $Call.ByID(2839243450, projectPath, assetId, name, assetTypeId, isResource, pointer, tags);
}

/**
 * UpdateAssetDependencySelector changes a dependency edge selector.
 * @param {string} projectPath
 * @param {string} assetId
 * @param {string} edgeId
 * @param {string} resolutionMode
 * @param {string} checkpointId
 * @param {string} checkpointGroupTagId
 * @returns {$CancellablePromise<models$0.AssetDependencyEdge>}
 */
export function UpdateAssetDependencySelector(projectPath, assetId, edgeId, resolutionMode, checkpointId, checkpointGroupTagId) {
    return $Call.ByID(2704534518, projectPath, assetId, edgeId, resolutionMode, checkpointId, checkpointGroupTagId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} id
 * @param {string} name
 * @param {string} icon
 * @returns {$CancellablePromise<models$0.AssetType>}
 */
export function UpdateAssetType(projectPath, id, name, icon) {
    return $Call.ByID(865399386, projectPath, id, name, icon).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.AssetDependencyEdge.createFrom;
const $$createType1 = models$0.AssetDependency.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.MetadataUpdateResult.createFrom;
const $$createType4 = models$0.AssetType.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $Create.Array($$createType4);
const $$createType9 = $models.AssetsStates.createFrom;
const $$createType10 = models$0.DependencySelectorOptions.createFrom;
const $$createType11 = $Create.Array($Create.Any);
