// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repository$0 from "../internal/repository/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCheckpoint creates new checkpoints for multiple assets.
 * Returns the created checkpoints or an error if the operation fails.
 * @param {string} projectPath
 * @param {string[]} assetPaths
 * @param {string[]} extensions
 * @param {string} message
 * @param {string} previewPath
 * @param {string} groupId
 * @param {boolean} useAsThumbnail
 * @param {boolean} sendToIntegration
 * @returns {$CancellablePromise<models$0.Checkpoint[]>}
 */
export function AddCheckpoint(projectPath, assetPaths, extensions, message, previewPath, groupId, useAsThumbnail, sendToIntegration) {
    return $Call.ByID(3142003966, projectPath, assetPaths, extensions, message, previewPath, groupId, useAsThumbnail, sendToIntegration).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function AddMissingGroupIds(projectPath) {
    return $Call.ByID(2914642103, projectPath);
}

/**
 * AddUntrackedAsset tracks previously untracked files and creates checkpoints for them.
 * Returns the newly tracked assets or an error if the operation fails.
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} assetPaths
 * @param {number} completed
 * @param {number} totalAssets
 * @param {string} message
 * @param {string} previewPath
 * @param {string} groupId
 * @returns {$CancellablePromise<models$0.Asset[]>}
 */
export function AddUntrackedAsset(projectPath, projectWorkingDir, assetPaths, completed, totalAssets, message, previewPath, groupId) {
    return $Call.ByID(3571873797, projectPath, projectWorkingDir, assetPaths, completed, totalAssets, message, previewPath, groupId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteCheckpoint removes a checkpoint from the project.
 * Returns an error if the deletion fails.
 * @param {string} projectPath
 * @param {string} checkpointId
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCheckpoint(projectPath, checkpointId) {
    return $Call.ByID(4189987792, projectPath, checkpointId);
}

/**
 * DeleteCheckpointTag removes an unreferenced checkpoint tag.
 * @param {string} projectPath
 * @param {string} tagId
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCheckpointTag(projectPath, tagId) {
    return $Call.ByID(1020568464, projectPath, tagId);
}

/**
 * ExecuteDependencyBuildPlan restores a freshly revalidated exact-checkpoint plan.
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string} rootAssetId
 * @param {string} expectedFingerprint
 * @param {boolean} allowModified
 * @returns {$CancellablePromise<models$0.DependencyBuildResult>}
 */
export function ExecuteDependencyBuildPlan(projectPath, remoteUrl, rootAssetId, expectedFingerprint, allowModified) {
    return $Call.ByID(2431386892, projectPath, remoteUrl, rootAssetId, expectedFingerprint, allowModified).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCheckpointDependencyReferenceCounts returns exact-pin follower counts for an asset.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<{ [_: string]: number }>}
 */
export function GetCheckpointDependencyReferenceCounts(projectPath, assetId) {
    return $Call.ByID(629976125, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetCheckpointTags returns the moving tags defined for an asset.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.AssetCheckpointTag[]>}
 */
export function GetCheckpointTags(projectPath, assetId) {
    return $Call.ByID(992419540, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetCheckpoints retrieves all checkpoints for a specific asset.
 * Returns the list of checkpoints or an error if the operation fails.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.Checkpoint[]>}
 */
export function GetCheckpoints(projectPath, assetId) {
    return $Call.ByID(4053110126, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLatestCheckpoint retrieves the most recent checkpoint for a asset.
 * Returns the latest checkpoint or an error if not found.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.Checkpoint>}
 */
export function GetLatestCheckpoint(projectPath, assetId) {
    return $Call.ByID(1994898182, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTimeline retrieves the project timeline showing checkpoint history.
 * Returns the timeline data or an error if the operation fails.
 * @param {string} projectPath
 * @returns {$CancellablePromise<repository$0.CompatTimeline[]>}
 */
export function GetTimeline(projectPath) {
    return $Call.ByID(3258604816, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Revert reverts multiple assets to their latest checkpoints.
 * Downloads missing chunks if needed and supports cancellation.
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<$models.FetchResult>}
 */
export function Revert(projectPath, remoteUrl, assetIds) {
    return $Call.ByID(3999685591, projectPath, remoteUrl, assetIds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RevertAssetPaths reverts assets by their file paths to latest checkpoints.
 * Downloads missing chunks if needed and supports cancellation.
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string[]} assetPaths
 * @returns {$CancellablePromise<void>}
 */
export function RevertAssetPaths(projectPath, remoteUrl, assetPaths) {
    return $Call.ByID(1619220907, projectPath, remoteUrl, assetPaths);
}

/**
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string} checkpointTime
 * @returns {$CancellablePromise<void>}
 */
export function RevertProject(projectPath, remoteUrl, checkpointTime) {
    return $Call.ByID(3684843780, projectPath, remoteUrl, checkpointTime);
}

/**
 * RevertToCheckpoint reverts a asset to a specific checkpoint state.
 * Downloads missing chunks if needed and supports cancellation.
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string} assetId
 * @param {string} checkpointId
 * @returns {$CancellablePromise<void>}
 */
export function RevertToCheckpoint(projectPath, remoteUrl, assetId, checkpointId) {
    return $Call.ByID(1668596852, projectPath, remoteUrl, assetId, checkpointId);
}

/**
 * SetCheckpointTag creates, renames, or moves an asset-scoped tag.
 * @param {string} projectPath
 * @param {string} tagId
 * @param {string} name
 * @param {string} checkpointId
 * @returns {$CancellablePromise<models$0.AssetCheckpointTag>}
 */
export function SetCheckpointTag(projectPath, tagId, name, checkpointId) {
    return $Call.ByID(4000678219, projectPath, tagId, name, checkpointId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SetCheckpointTagsForGroup applies one tag name to each checkpoint in a group.
 * @param {string} projectPath
 * @param {string} name
 * @param {string} groupId
 * @returns {$CancellablePromise<models$0.AssetCheckpointTag[]>}
 */
export function SetCheckpointTagsForGroup(projectPath, name, groupId) {
    return $Call.ByID(2098049918, projectPath, name, groupId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SquashAssets combines multiple untracked files into a single asset with sequential checkpoints.
 * The first file becomes the initial checkpoint, and subsequent files are added as additional checkpoints.
 * @param {string} projectPath
 * @param {string} projectWorkingDir
 * @param {string[]} filePaths
 * @param {string} assetName
 * @param {string} collectionId
 * @param {boolean} deleteSourceFiles
 * @param {string[]} checkpointComments
 * @returns {$CancellablePromise<models$0.Asset>}
 */
export function SquashAssets(projectPath, projectWorkingDir, filePaths, assetName, collectionId, deleteSourceFiles, checkpointComments) {
    return $Call.ByID(2209883097, projectPath, projectWorkingDir, filePaths, assetName, collectionId, deleteSourceFiles, checkpointComments);
}

/**
 * ViewCheckpoint creates a temporary file from a checkpoint and opens it.
 * The temp file is placed in the same directory as the original asset so relative dependencies resolve correctly.
 * @param {string} projectPath
 * @param {string} checkpointId
 * @param {string} assetId
 * @param {string} collectionName
 * @param {string} extension
 * @returns {$CancellablePromise<void>}
 */
export function ViewCheckpoint(projectPath, checkpointId, assetId, collectionName, extension) {
    return $Call.ByID(674726738, projectPath, checkpointId, assetId, collectionName, extension);
}

// Private type creation functions
const $$createType0 = models$0.Checkpoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = models$0.DependencyBuildResult.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = models$0.AssetCheckpointTag.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = repository$0.CompatTimeline.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.FetchResult.createFrom;
