// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Assign assigns a user to a collection.
 * Returns an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} userId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Assign(projectPath, entityId, userId) {
    let $resultPromise = /** @type {any} */($Call.ByID(2838915874, projectPath, entityId, userId));
    return $resultPromise;
}

/**
 * ChangeCollectionParent moves one or more collections to a different parent collection.
 * Checks for name conflicts in the target parent before moving.
 * Returns an error if any collection would conflict or if the operation fails.
 * @param {string} projectPath
 * @param {string[]} entityIds
 * @param {string} parentId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ChangeCollectionParent(projectPath, entityIds, parentId) {
    let $resultPromise = /** @type {any} */($Call.ByID(2168719759, projectPath, entityIds, parentId));
    return $resultPromise;
}

/**
 * ChangeIsLibrary toggles the library flag on a collection.
 * Returns an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {boolean} isLibrary
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ChangeIsLibrary(projectPath, entityId, isLibrary) {
    let $resultPromise = /** @type {any} */($Call.ByID(2948869046, projectPath, entityId, isLibrary));
    return $resultPromise;
}

/**
 * ChangeType changes the type of a collection.
 * Returns an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} entityTypeId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ChangeType(projectPath, entityId, entityTypeId) {
    let $resultPromise = /** @type {any} */($Call.ByID(489875783, projectPath, entityId, entityTypeId));
    return $resultPromise;
}

/**
 * CreateCollection creates a new collection in the project.
 * Returns the created entity or an error if the operation fails.
 * @param {string} projectPath
 * @param {string} name
 * @param {string} description
 * @param {string} entityTypeId
 * @param {string} parentId
 * @param {string} previewPath
 * @param {boolean} isLibrary
 * @returns {Promise<models$0.Entity> & { cancel(): void }}
 */
export function CreateCollection(projectPath, name, description, entityTypeId, parentId, previewPath, isLibrary) {
    let $resultPromise = /** @type {any} */($Call.ByID(1857306755, projectPath, name, description, entityTypeId, parentId, previewPath, isLibrary));
    return $resultPromise;
}

/**
 * CreateCollectionType creates a new collection type in the project.
 * Returns an error if a type with the same name already exists.
 * @param {string} projectPath
 * @param {string} entityTypeName
 * @param {string} entityTypeIcon
 * @returns {Promise<models$0.EntityType> & { cancel(): void }}
 */
export function CreateCollectionType(projectPath, entityTypeName, entityTypeIcon) {
    let $resultPromise = /** @type {any} */($Call.ByID(4202352859, projectPath, entityTypeName, entityTypeIcon));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * CreateCollections creates multiple collection entities in bulk.
 * Currently a stub implementation for future batch creation functionality.
 * @param {string} projectPath
 * @param {string} name
 * @param {string} description
 * @param {string} entityTypeId
 * @param {string} parentId
 * @returns {Promise<models$0.Entity[]> & { cancel(): void }}
 */
export function CreateCollections(projectPath, name, description, entityTypeId, parentId) {
    let $resultPromise = /** @type {any} */($Call.ByID(901921232, projectPath, name, description, entityTypeId, parentId));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteCollection removes a collection from the project.
 * Optionally removes associated files if removeFiles is true.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {boolean} removeFiles
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteCollection(projectPath, entityId, removeFiles) {
    let $resultPromise = /** @type {any} */($Call.ByID(3363308644, projectPath, entityId, removeFiles));
    return $resultPromise;
}

/**
 * DeleteCollectionType removes a collection type from the project.
 * Returns an error if the operation fails.
 * @param {string} projectPath
 * @param {string} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteCollectionType(projectPath, id) {
    let $resultPromise = /** @type {any} */($Call.ByID(2991338316, projectPath, id));
    return $resultPromise;
}

/**
 * GetCollectionByID retrieves a collection by its ID.
 * Returns the entity or an error if not found.
 * @param {string} projectPath
 * @param {string} entityId
 * @returns {Promise<models$0.Entity> & { cancel(): void }}
 */
export function GetCollectionByID(projectPath, entityId) {
    let $resultPromise = /** @type {any} */($Call.ByID(1116836093, projectPath, entityId));
    return $resultPromise;
}

/**
 * GetCollectionByPath retrieves a collection by its filesystem path.
 * Returns the entity or an error if not found.
 * @param {string} projectPath
 * @param {string} entityPath
 * @returns {Promise<models$0.Entity> & { cancel(): void }}
 */
export function GetCollectionByPath(projectPath, entityPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(2488608455, projectPath, entityPath));
    return $resultPromise;
}

/**
 * GetCollectionChildren retrieves all children of a collection including tracked and untracked items.
 * Returns separate lists for tasks, entities, and untracked items.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} projectWorkingDir
 * @param {string} entityFolderPath
 * @param {string[]} ignoreList
 * @param {boolean} isUntracked
 * @returns {Promise<$models.EntityItems> & { cancel(): void }}
 */
export function GetCollectionChildren(projectPath, entityId, projectWorkingDir, entityFolderPath, ignoreList, isUntracked) {
    let $resultPromise = /** @type {any} */($Call.ByID(985363246, projectPath, entityId, projectWorkingDir, entityFolderPath, ignoreList, isUntracked));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType2($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollectionChildrenState analyzes the immediate children of a collection to determine their state.
 * Returns state containing modified, outdated, rebuildable tasks and untracked items.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {Promise<$models.CollectionChildrenState> & { cancel(): void }}
 */
export function GetCollectionChildrenState(projectPath, entityId, projectWorkingDir, ignoreList) {
    let $resultPromise = /** @type {any} */($Call.ByID(1931303187, projectPath, entityId, projectWorkingDir, ignoreList));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollectionCount returns the total number of collections in the project.
 * Returns the count or an error if the operation fails.
 * @param {string} projectPath
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetCollectionCount(projectPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(773498904, projectPath));
    return $resultPromise;
}

/**
 * GetCollectionStateFlags checks if a collection has any recursive children with specific states.
 * Returns flags indicating presence of untracked, modified, outdated, or rebuildable items.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {Promise<$models.CollectionStateFlags> & { cancel(): void }}
 */
export function GetCollectionStateFlags(projectPath, entityId, projectWorkingDir, ignoreList) {
    let $resultPromise = /** @type {any} */($Call.ByID(144595661, projectPath, entityId, projectWorkingDir, ignoreList));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollectionTasks retrieves all tasks belonging to a specific collection.
 * Returns the list of tasks or an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @returns {Promise<models$0.Task[]> & { cancel(): void }}
 */
export function GetCollectionTasks(projectPath, entityId) {
    let $resultPromise = /** @type {any} */($Call.ByID(1367523417, projectPath, entityId));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollectionTypes retrieves all collection types in the project.
 * Returns the list of entity types or an error if the operation fails.
 * @param {string} projectPath
 * @returns {Promise<models$0.EntityType[]> & { cancel(): void }}
 */
export function GetCollectionTypes(projectPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1279663726, projectPath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType6($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCollections retrieves collections based on user permissions.
 * Returns all entities or only user-accessible entities based on role.
 * @param {string} projectPath
 * @returns {Promise<models$0.Entity[]> & { cancel(): void }}
 */
export function GetCollections(projectPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(1787506934, projectPath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetItemsForCheckpoint efficiently collects all modified and untracked items in a collection hierarchy.
 * Returns deduplicated modified tasks and untracked files.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} targetPath
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {Promise<$models.ItemsForCheckpoint> & { cancel(): void }}
 */
export function GetItemsForCheckpoint(projectPath, entityId, targetPath, projectWorkingDir, ignoreList) {
    let $resultPromise = /** @type {any} */($Call.ByID(621025292, projectPath, entityId, targetPath, projectWorkingDir, ignoreList));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType7($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetOutdatedItemsInCollection efficiently collects all outdated items in a collection hierarchy.
 * Returns deduplicated outdated tasks.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {Promise<$models.ItemsForUpdate> & { cancel(): void }}
 */
export function GetOutdatedItemsInCollection(projectPath, entityId, projectWorkingDir, ignoreList) {
    let $resultPromise = /** @type {any} */($Call.ByID(86452480, projectPath, entityId, projectWorkingDir, ignoreList));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType8($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * Rebuild downloads missing checkpoints and rebuilds files for specified collections.
 * Supports cancellation and sends progress updates via application events.
 * @param {string} projectPath
 * @param {string} remoteUrl
 * @param {string} entityIds
 * @param {string} userId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Rebuild(projectPath, remoteUrl, entityIds, userId) {
    let $resultPromise = /** @type {any} */($Call.ByID(1269618418, projectPath, remoteUrl, entityIds, userId));
    return $resultPromise;
}

/**
 * RenameCollection renames an existing collection.
 * Returns the updated entity or an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} newName
 * @returns {Promise<models$0.Entity> & { cancel(): void }}
 */
export function RenameCollection(projectPath, entityId, newName) {
    let $resultPromise = /** @type {any} */($Call.ByID(3064640869, projectPath, entityId, newName));
    return $resultPromise;
}

/**
 * RevealCollection opens the file explorer to show a collection's folder.
 * Returns an error if the entity is not found or the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RevealCollection(projectPath, entityId) {
    let $resultPromise = /** @type {any} */($Call.ByID(1753210934, projectPath, entityId));
    return $resultPromise;
}

/**
 * RevertCollections reverts multiple collections to their latest checkpoints.
 * Sends progress updates for each entity processed.
 * @param {string} projectPath
 * @param {string[]} entityIds
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RevertCollections(projectPath, entityIds) {
    let $resultPromise = /** @type {any} */($Call.ByID(1570908726, projectPath, entityIds));
    return $resultPromise;
}

/**
 * Unassign removes a user assignment from a collection.
 * Returns an error if the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} userId
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Unassign(projectPath, entityId, userId) {
    let $resultPromise = /** @type {any} */($Call.ByID(3540910669, projectPath, entityId, userId));
    return $resultPromise;
}

/**
 * UpdateCollectionType updates an existing collection type.
 * Returns an error if a type with the new name already exists.
 * @param {string} projectPath
 * @param {string} id
 * @param {string} entityTypeName
 * @param {string} entityTypeIcon
 * @returns {Promise<models$0.EntityType> & { cancel(): void }}
 */
export function UpdateCollectionType(projectPath, id, entityTypeName, entityTypeIcon) {
    let $resultPromise = /** @type {any} */($Call.ByID(4261460618, projectPath, id, entityTypeName, entityTypeIcon));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * UpdatePreview updates the preview image for a collection.
 * Returns an error if the project is not found or the operation fails.
 * @param {string} projectPath
 * @param {string} entityId
 * @param {string} previewPath
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdatePreview(projectPath, entityId, previewPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(406683254, projectPath, entityId, previewPath));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = models$0.EntityType.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.EntityItems.createFrom;
const $$createType3 = $models.CollectionChildrenState.createFrom;
const $$createType4 = $models.CollectionStateFlags.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $models.ItemsForCheckpoint.createFrom;
const $$createType8 = $models.ItemsForUpdate.createFrom;
