// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * GetDependencyTypes retrieves all dependency types in the project.
 * Returns the list of dependency types or an error if the operation fails.
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.DependencyType[]>}
 */
export function GetDependencyTypes(projectPath) {
    return $Call.ByID(2647661960, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.DependencyType.createFrom;
const $$createType1 = $Create.Array($$createType0);
