// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeployStudio initiates a new studio deployment on Azure.
 * Returns the deployment response with ID and WebSocket URL, or an error if deployment fails.
 * @param {$models.DeploymentRequest} request
 * @returns {$CancellablePromise<$models.DeploymentResponse | null>}
 */
export function DeployStudio(request) {
    return $Call.ByID(1278471293, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DestroyDeployment tears down a studio deployment and releases Azure resources.
 * Returns an error if the destruction fails.
 * @param {string} deploymentID
 * @returns {$CancellablePromise<void>}
 */
export function DestroyDeployment(deploymentID) {
    return $Call.ByID(1013268829, deploymentID);
}

/**
 * GetDeploymentStatus retrieves the current status of a deployment.
 * Returns the deployment status details or an error if the request fails.
 * @param {string} deploymentID
 * @returns {$CancellablePromise<$models.DeploymentStatus | null>}
 */
export function GetDeploymentStatus(deploymentID) {
    return $Call.ByID(3266850961, deploymentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DeploymentResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DeploymentStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
