// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SaveFileDialog opens a file dialog for an export destination.
 * Returns the selected path or an empty string if cancelled.
 * @param {string} title
 * @param {string} filename
 * @param {string} filterName
 * @param {string} filterPattern
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(title, filename, filterName, filterPattern) {
    return $Call.ByID(1432736924, title, filename, filterName, filterPattern);
}

/**
 * SelectFileDialog opens a file dialog with custom title and filters.
 * Returns the selected file path or an empty string if cancelled.
 * @param {string} title
 * @param {string} filters
 * @returns {$CancellablePromise<string>}
 */
export function SelectFileDialog(title, filters) {
    return $Call.ByID(3383516309, title, filters);
}

/**
 * SelectFilesDialog opens a file dialog to select multiple files.
 * Returns the selected file paths or an empty list if cancelled.
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectFilesDialog() {
    return $Call.ByID(614873094).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SelectFolderDialog opens a folder selection dialog with a custom title.
 * Returns the selected folder path or an empty string if cancelled.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolderDialog(title) {
    return $Call.ByID(1248956583, title);
}

/**
 * SelectIconDialog opens a file dialog to select an icon image.
 * Returns the base64-encoded resized icon or an error.
 * @returns {$CancellablePromise<string>}
 */
export function SelectIconDialog() {
    return $Call.ByID(1084525214);
}

/**
 * SelectItemsDialog opens a dialog to select multiple files or directories.
 * Returns the selected paths or an empty list if cancelled.
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectItemsDialog() {
    return $Call.ByID(2162344469).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SelectSpecificFolderDialog opens a folder dialog with a default starting path.
 * Returns the selected folder path or an error.
 * @param {string} title
 * @param {string} defaultPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectSpecificFolderDialog(title, defaultPath) {
    return $Call.ByID(4244729795, title, defaultPath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
