// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DragService handles native OS drag-and-drop operations.
 * Platform-specific implementations initiate OS-level drag when files
 * are dragged outside the application window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IsMouseButtonDown checks if the left mouse button is currently pressed.
 * Used by frontend to verify drag state before initiating native drag.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMouseButtonDown() {
    return $Call.ByID(477326228);
}

/**
 * StartNativeDrag initiates a native Windows drag-and-drop operation.
 * This function blocks until the user completes or cancels the drag.
 * Returns the drop effect (copy, move, link, or none).
 * @param {string[]} filePaths
 * @returns {$CancellablePromise<number>}
 */
export function StartNativeDrag(filePaths) {
    return $Call.ByID(1327461126, filePaths);
}
