// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetEntitlements fetches the current user's entitlement bundle from the server.
 * @returns {$CancellablePromise<$models.EntitlementBundle>}
 */
export function GetEntitlements() {
    return $Call.ByID(2005214572).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStudioEntitlements fetches entitlements for a specific studio.
 * @param {string} studioId
 * @returns {$CancellablePromise<$models.EntitlementBundle>}
 */
export function GetStudioEntitlements(studioId) {
    return $Call.ByID(1004503926, studioId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.EntitlementBundle.createFrom;
