// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePlan changes the subscription to a new plan and returns the updated entitlements.
 * @param {string} planId
 * @returns {$CancellablePromise<$models.EntitlementBundle>}
 */
export function ChangePlan(planId) {
    return $Call.ByID(1517853031, planId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateCheckout creates a Stripe Checkout Session and returns the checkout URL.
 * @param {string} planId
 * @param {string} studioId
 * @returns {$CancellablePromise<string>}
 */
export function CreateCheckout(planId, studioId) {
    return $Call.ByID(2200075884, planId, studioId);
}

/**
 * GetEntitlements fetches the current user's entitlement bundle from the server.
 * @returns {$CancellablePromise<$models.EntitlementBundle>}
 */
export function GetEntitlements() {
    return $Call.ByID(2005214572).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetPlans fetches all available plans from the server.
 * @returns {$CancellablePromise<$models.Plan[]>}
 */
export function GetPlans() {
    return $Call.ByID(3186353408).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetStudioEntitlements fetches entitlements for a specific studio.
 * @param {string} studioId
 * @returns {$CancellablePromise<$models.EntitlementBundle>}
 */
export function GetStudioEntitlements(studioId) {
    return $Call.ByID(1004503926, studioId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenBillingPortal creates a Stripe Billing Portal session and returns the portal URL.
 * @returns {$CancellablePromise<string>}
 */
export function OpenBillingPortal() {
    return $Call.ByID(308026693);
}

// Private type creation functions
const $$createType0 = $models.EntitlementBundle.createFrom;
const $$createType1 = $models.Plan.createFrom;
const $$createType2 = $Create.Array($$createType1);
