// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @param {models$0.Entity[]} entities
 * @param {number} completed
 * @param {number} totalEntities
 * @returns {$CancellablePromise<void>}
 */
export function CreateEntities(projectPath, entities, completed, totalEntities) {
    return $Call.ByID(1462445845, projectPath, entities, completed, totalEntities);
}

/**
 * @param {string} projectPath
 * @param {models$0.Entity[]} entities
 * @param {models$0.Task[]} tasks
 * @param {string} comment
 * @param {string} groupId
 * @returns {$CancellablePromise<void>}
 */
export function CreateItems(projectPath, entities, tasks, comment, groupId) {
    return $Call.ByID(1562194358, projectPath, entities, tasks, comment, groupId);
}

/**
 * @param {string} projectPath
 * @param {models$0.Task[]} tasks
 * @param {number} completed
 * @param {number} totalTasks
 * @param {string} comment
 * @param {string} groupId
 * @returns {$CancellablePromise<void>}
 */
export function CreateTasks(projectPath, tasks, completed, totalTasks, comment, groupId) {
    return $Call.ByID(3633228444, projectPath, tasks, completed, totalTasks, comment, groupId);
}

/**
 * @param {string} projectPath
 * @param {string} parentId
 * @param {string[]} folders
 * @param {string[]} files
 * @param {string} projectWorkingDir
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<$models.ImportItems>}
 */
export function ImportFolder(projectPath, parentId, folders, files, projectWorkingDir, ignoreList) {
    return $Call.ByID(2443458599, projectPath, parentId, folders, files, projectWorkingDir, ignoreList).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ImportItems.createFrom;
