// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IntegrationService handles external integration operations (Kitsu, ClickUp, etc.)
 * Exposed to frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as integrations$0 from "../internal/integrations/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * Authenticate authenticates with an external integration.
 * Returns auth result with user info and token on success.
 * @param {string} integrationId
 * @param {{ [_: string]: string }} credentials
 * @returns {$CancellablePromise<integrations$0.AuthResult>}
 */
export function Authenticate(integrationId, credentials) {
    return $Call.ByID(3839669716, integrationId, credentials).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExecuteSync stores mappings for selected external items.
 * Collections and assets are not automatically created - users create them manually
 * and the mappings help track what's been imported.
 * @param {string} projectPath
 * @param {string} token
 * @param {string[]} selectedCollections
 * @param {string[]} selectedAssets
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteSync(projectPath, token, selectedCollections, selectedAssets) {
    return $Call.ByID(2812294731, projectPath, token, selectedCollections, selectedAssets);
}

/**
 * GetAssetExternalInfo returns the external info for a synced asset.
 * @param {string} projectPath
 * @param {string} assetId
 * @returns {$CancellablePromise<models$0.IntegrationAssetMapping>}
 */
export function GetAssetExternalInfo(projectPath, assetId) {
    return $Call.ByID(1413996838, projectPath, assetId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAssetMappings returns all asset mappings for the project.
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.IntegrationAssetMapping[]>}
 */
export function GetAssetMappings(projectPath) {
    return $Call.ByID(3345844702, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAvailableIntegrations returns all registered integrations.
 * Each integration contains id, name, description, and auth requirements.
 * @returns {$CancellablePromise<integrations$0.IntegrationInfo[]>}
 */
export function GetAvailableIntegrations() {
    return $Call.ByID(493987065).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetCollectionExternalInfo returns the external info for a synced collection.
 * @param {string} projectPath
 * @param {string} collectionId
 * @returns {$CancellablePromise<models$0.IntegrationCollectionMapping>}
 */
export function GetCollectionExternalInfo(projectPath, collectionId) {
    return $Call.ByID(1536579992, projectPath, collectionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCollectionMappings returns all collection mappings for the project.
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.IntegrationCollectionMapping[]>}
 */
export function GetCollectionMappings(projectPath) {
    return $Call.ByID(3275970800, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetExternalProjects fetches available projects from an external integration.
 * Requires valid token for the integration.
 * @param {string} integrationId
 * @param {string} token
 * @param {string} apiUrl
 * @returns {$CancellablePromise<integrations$0.ExternalProject[]>}
 */
export function GetExternalProjects(integrationId, token, apiUrl) {
    return $Call.ByID(3926678990, integrationId, token, apiUrl).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetIntegration returns info for a specific integration by ID.
 * @param {string} integrationId
 * @returns {$CancellablePromise<integrations$0.IntegrationInfo>}
 */
export function GetIntegration(integrationId) {
    return $Call.ByID(1677600143, integrationId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetLinkedIntegration returns the integration linked to a project.
 * Returns empty struct if no integration is linked.
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.IntegrationProject>}
 */
export function GetLinkedIntegration(projectPath) {
    return $Call.ByID(3555362308, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetSyncPreview fetches external hierarchy and compares with local state.
 * Returns preview of what will be created/updated/unchanged.
 * @param {string} projectPath
 * @param {string} token
 * @returns {$CancellablePromise<integrations$0.SyncPreview>}
 */
export function GetSyncPreview(projectPath, token) {
    return $Call.ByID(1539504252, projectPath, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * LinkProject links a Clustta project to an external project.
 * Returns error if project already has an integration.
 * @param {string} projectPath
 * @param {string} integrationId
 * @param {string} externalProjectId
 * @param {string} externalProjectName
 * @param {string} apiUrl
 * @param {string} syncOptions
 * @param {string} userId
 * @returns {$CancellablePromise<models$0.IntegrationProject>}
 */
export function LinkProject(projectPath, integrationId, externalProjectId, externalProjectName, apiUrl, syncOptions, userId) {
    return $Call.ByID(3276450698, projectPath, integrationId, externalProjectId, externalProjectName, apiUrl, syncOptions, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * UnlinkProject removes the integration link from a project.
 * Also deletes all collection and asset mappings.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function UnlinkProject(projectPath) {
    return $Call.ByID(659669611, projectPath);
}

/**
 * ValidateToken validates an existing token is still valid.
 * @param {string} integrationId
 * @param {string} token
 * @param {string} apiUrl
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateToken(integrationId, token, apiUrl) {
    return $Call.ByID(2669007040, integrationId, token, apiUrl);
}

// Private type creation functions
const $$createType0 = integrations$0.AuthResult.createFrom;
const $$createType1 = models$0.IntegrationAssetMapping.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = integrations$0.IntegrationInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.IntegrationCollectionMapping.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = integrations$0.ExternalProject.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.IntegrationProject.createFrom;
const $$createType10 = integrations$0.SyncPreview.createFrom;
