// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IntegrationService handles external integration operations (Kitsu, etc.)
 * Exposed to frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as integrations$0 from "../internal/integrations/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * Authenticate authenticates with an external integration.
 * Returns auth result with user info and token on success.
 * @param {string} integrationId
 * @param {{ [_: string]: string }} credentials
 * @returns {$CancellablePromise<integrations$0.AuthResult>}
 */
export function Authenticate(integrationId, credentials) {
    return $Call.ByID(3839669716, integrationId, credentials).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateMissingTypes creates collection and asset types in Clustta for missing external types.
 * Updates sync_options with the new mappings.
 * @param {string} projectPath
 * @param {integrations$0.MissingType[]} missingTypes
 * @returns {$CancellablePromise<void>}
 */
export function CreateMissingTypes(projectPath, missingTypes) {
    return $Call.ByID(3078528372, projectPath, missingTypes);
}

/**
 * ExecuteSync creates Clustta collections and assets from the provided sync preview data.
 * Accepts collections and assets from frontend instead of re-fetching from integration.
 * Creates all items - collections sorted by path depth (parents first), then assets with templates.
 * @param {string} projectPath
 * @param {string} collectionsJSON
 * @param {string} assetsJSON
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteSync(projectPath, collectionsJSON, assetsJSON) {
    return $Call.ByID(2812294731, projectPath, collectionsJSON, assetsJSON);
}

/**
 * GetAvailableIntegrations returns all registered integrations.
 * Each integration contains id, name, description, and auth requirements.
 * @returns {$CancellablePromise<integrations$0.IntegrationInfo[]>}
 */
export function GetAvailableIntegrations() {
    return $Call.ByID(493987065).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetExternalProjects fetches available projects from an external integration.
 * Requires valid token for the integration.
 * @param {string} integrationId
 * @param {string} token
 * @param {string} apiUrl
 * @returns {$CancellablePromise<integrations$0.ExternalProject[]>}
 */
export function GetExternalProjects(integrationId, token, apiUrl) {
    return $Call.ByID(3926678990, integrationId, token, apiUrl).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetExternalStatuses fetches task statuses from the external integration.
 * Returns the list of available statuses for mapping.
 * @param {string} projectPath
 * @param {string} token
 * @returns {$CancellablePromise<integrations$0.ExternalStatusInfo[]>}
 */
export function GetExternalStatuses(projectPath, token) {
    return $Call.ByID(2866478662, projectPath, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetExternalTypes fetches collection and asset types from the external integration.
 * Requires valid token and linked integration.
 * @param {string} projectPath
 * @param {string} token
 * @returns {$CancellablePromise<[integrations$0.ExternalTypeInfo[], integrations$0.ExternalTypeInfo[]]>}
 */
export function GetExternalTypes(projectPath, token) {
    return $Call.ByID(1578626957, projectPath, token).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType8($result[0]);
        $result[1] = $$createType8($result[1]);
        return $result;
    }));
}

/**
 * GetLinkedIntegration returns the integration linked to a project.
 * Returns empty struct if no integration is linked.
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.IntegrationProject>}
 */
export function GetLinkedIntegration(projectPath) {
    return $Call.ByID(3555362308, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetLocalTypes returns all collection and asset types from the project.
 * Used by frontend to populate mapping dropdowns.
 * @param {string} projectPath
 * @returns {$CancellablePromise<[models$0.CollectionType[], models$0.AssetType[]]>}
 */
export function GetLocalTypes(projectPath) {
    return $Call.ByID(443978039, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType11($result[0]);
        $result[1] = $$createType13($result[1]);
        return $result;
    }));
}

/**
 * GetMissingTypes compares external types with local Clustta types.
 * Returns types that don't have a mapping in sync_options and don't exist in Clustta.
 * @param {string} projectPath
 * @param {string} token
 * @returns {$CancellablePromise<integrations$0.MissingType[]>}
 */
export function GetMissingTypes(projectPath, token) {
    return $Call.ByID(3905082754, projectPath, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetSyncPreview fetches the external hierarchy and classifies every enabled item.
 * Items are marked for creation, linking to a local match, or no action.
 * @param {string} projectPath
 * @param {string} token
 * @returns {$CancellablePromise<integrations$0.SyncPreview>}
 */
export function GetSyncPreview(projectPath, token) {
    return $Call.ByID(1539504252, projectPath, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetTypeMappings retrieves the type mappings from sync_options for a project.
 * Returns empty SyncOptions if no mappings configured yet.
 * @param {string} projectPath
 * @returns {$CancellablePromise<integrations$0.SyncOptions>}
 */
export function GetTypeMappings(projectPath) {
    return $Call.ByID(2092174792, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * LinkProject links a Clustta project to an external project.
 * Returns error if project already has an integration.
 * @param {string} projectPath
 * @param {string} integrationId
 * @param {string} externalProjectId
 * @param {string} externalProjectName
 * @param {string} apiUrl
 * @param {string} syncOptions
 * @param {string} userId
 * @returns {$CancellablePromise<models$0.IntegrationProject>}
 */
export function LinkProject(projectPath, integrationId, externalProjectId, externalProjectName, apiUrl, syncOptions, userId) {
    return $Call.ByID(3276450698, projectPath, integrationId, externalProjectId, externalProjectName, apiUrl, syncOptions, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * PushToIntegration pushes a checkpoint's preview and status to the linked external integration.
 * Returns an error if the push fails. A nil error means the push completed (or was skipped).
 * @param {string} projectPath
 * @param {string[]} assetIds
 * @param {string} checkpointId
 * @param {string} previewPath
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function PushToIntegration(projectPath, assetIds, checkpointId, previewPath, message) {
    return $Call.ByID(224699366, projectPath, assetIds, checkpointId, previewPath, message);
}

/**
 * SaveStatusMappings saves status mappings to sync_options (Clustta status ID → external status ID).
 * @param {string} projectPath
 * @param {{ [_: string]: string }} statusMappings
 * @returns {$CancellablePromise<void>}
 */
export function SaveStatusMappings(projectPath, statusMappings) {
    return $Call.ByID(1555028661, projectPath, statusMappings);
}

/**
 * SaveTypeMappings saves type mappings to sync_options for a project.
 * @param {string} projectPath
 * @param {integrations$0.SyncOptions} syncOptions
 * @returns {$CancellablePromise<void>}
 */
export function SaveTypeMappings(projectPath, syncOptions) {
    return $Call.ByID(2486271679, projectPath, syncOptions);
}

/**
 * UnlinkProject removes the integration link and its project mappings.
 * User-scoped credentials remain available to other linked projects.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function UnlinkProject(projectPath) {
    return $Call.ByID(659669611, projectPath);
}

// Private type creation functions
const $$createType0 = integrations$0.AuthResult.createFrom;
const $$createType1 = integrations$0.IntegrationInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = integrations$0.ExternalProject.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = integrations$0.ExternalStatusInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = integrations$0.ExternalTypeInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.IntegrationProject.createFrom;
const $$createType10 = models$0.CollectionType.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.AssetType.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = integrations$0.MissingType.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = integrations$0.SyncPreview.createFrom;
const $$createType17 = integrations$0.SyncOptions.createFrom;
