// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AssetStateItem {
    /**
     * Creates a new AssetStateItem instance.
     * @param {Partial<AssetStateItem>} [$$source = {}] - The source object to create the AssetStateItem.
     */
    constructor($$source = {}) {
        if (!("task_id" in $$source)) {
            /**
             * task ID for filtering
             * @member
             * @type {string}
             */
            this["task_id"] = "";
        }
        if (!("task_path" in $$source)) {
            /**
             * for checkpoints: "path/to/file"
             * @member
             * @type {string}
             */
            this["task_path"] = "";
        }
        if (!("display_path" in $$source)) {
            /**
             * for UI: "path/to/file.blend"
             * @member
             * @type {string}
             */
            this["display_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetStateItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetStateItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetStateItem(/** @type {Partial<AssetStateItem>} */($$parsedSource));
    }
}

export class AssetsStates {
    /**
     * Creates a new AssetsStates instance.
     * @param {Partial<AssetsStates>} [$$source = {}] - The source object to create the AssetsStates.
     */
    constructor($$source = {}) {
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {AssetStateItem[]}
             */
            this["modified"] = [];
        }
        if (!("rebuildable" in $$source)) {
            /**
             * @member
             * @type {AssetStateItem[]}
             */
            this["rebuildable"] = [];
        }
        if (!("outdated" in $$source)) {
            /**
             * @member
             * @type {AssetStateItem[]}
             */
            this["outdated"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetsStates instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetsStates}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified" in $$parsedSource) {
            $$parsedSource["modified"] = $$createField0_0($$parsedSource["modified"]);
        }
        if ("rebuildable" in $$parsedSource) {
            $$parsedSource["rebuildable"] = $$createField1_0($$parsedSource["rebuildable"]);
        }
        if ("outdated" in $$parsedSource) {
            $$parsedSource["outdated"] = $$createField2_0($$parsedSource["outdated"]);
        }
        return new AssetsStates(/** @type {Partial<AssetsStates>} */($$parsedSource));
    }
}

export class CollectionChildrenState {
    /**
     * Creates a new CollectionChildrenState instance.
     * @param {Partial<CollectionChildrenState>} [$$source = {}] - The source object to create the CollectionChildrenState.
     */
    constructor($$source = {}) {
        if (!("modified_tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["modified_tasks"] = [];
        }
        if (!("outdated_tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["outdated_tasks"] = [];
        }
        if (!("rebuildable_tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["rebuildable_tasks"] = [];
        }
        if (!("untracked_files" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedTask[]}
             */
            this["untracked_files"] = [];
        }
        if (!("untracked_folders" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedEntity[]}
             */
            this["untracked_folders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionChildrenState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectionChildrenState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified_tasks" in $$parsedSource) {
            $$parsedSource["modified_tasks"] = $$createField0_0($$parsedSource["modified_tasks"]);
        }
        if ("outdated_tasks" in $$parsedSource) {
            $$parsedSource["outdated_tasks"] = $$createField1_0($$parsedSource["outdated_tasks"]);
        }
        if ("rebuildable_tasks" in $$parsedSource) {
            $$parsedSource["rebuildable_tasks"] = $$createField2_0($$parsedSource["rebuildable_tasks"]);
        }
        if ("untracked_files" in $$parsedSource) {
            $$parsedSource["untracked_files"] = $$createField3_0($$parsedSource["untracked_files"]);
        }
        if ("untracked_folders" in $$parsedSource) {
            $$parsedSource["untracked_folders"] = $$createField4_0($$parsedSource["untracked_folders"]);
        }
        return new CollectionChildrenState(/** @type {Partial<CollectionChildrenState>} */($$parsedSource));
    }
}

export class CollectionStateFlags {
    /**
     * Creates a new CollectionStateFlags instance.
     * @param {Partial<CollectionStateFlags>} [$$source = {}] - The source object to create the CollectionStateFlags.
     */
    constructor($$source = {}) {
        if (!("has_untracked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_untracked"] = false;
        }
        if (!("has_modified" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_modified"] = false;
        }
        if (!("has_outdated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_outdated"] = false;
        }
        if (!("has_rebuildable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_rebuildable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectionStateFlags instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectionStateFlags}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectionStateFlags(/** @type {Partial<CollectionStateFlags>} */($$parsedSource));
    }
}

export class Country {
    /**
     * Creates a new Country instance.
     * @param {Partial<Country>} [$$source = {}] - The source object to create the Country.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Country instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Country}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Country(/** @type {Partial<Country>} */($$parsedSource));
    }
}

export class DeploymentRequest {
    /**
     * Creates a new DeploymentRequest instance.
     * @param {Partial<DeploymentRequest>} [$$source = {}] - The source object to create the DeploymentRequest.
     */
    constructor($$source = {}) {
        if (!("studio_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_name"] = "";
        }
        if (!("studio_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_url"] = "";
        }
        if (!("studio_secret_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_secret_key"] = "";
        }
        if (!("azure_region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["azure_region"] = "";
        }
        if (!("vm_size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vm_size"] = "";
        }
        if (!("disk_size_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["disk_size_gb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeploymentRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentRequest(/** @type {Partial<DeploymentRequest>} */($$parsedSource));
    }
}

export class DeploymentResponse {
    /**
     * Creates a new DeploymentResponse instance.
     * @param {Partial<DeploymentResponse>} [$$source = {}] - The source object to create the DeploymentResponse.
     */
    constructor($$source = {}) {
        if (!("deployment_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deployment_id"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("websocket_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["websocket_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeploymentResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentResponse(/** @type {Partial<DeploymentResponse>} */($$parsedSource));
    }
}

export class DeploymentStatus {
    /**
     * Creates a new DeploymentStatus instance.
     * @param {Partial<DeploymentStatus>} [$$source = {}] - The source object to create the DeploymentStatus.
     */
    constructor($$source = {}) {
        if (!("deployment_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deployment_id"] = "";
        }
        if (!("studio_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_name"] = "";
        }
        if (!("studio_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_url"] = "";
        }
        if (!("studio_secret_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_secret_key"] = "";
        }
        if (!("azure_region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["azure_region"] = "";
        }
        if (!("vm_size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vm_size"] = "";
        }
        if (!("disk_size_gb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["disk_size_gb"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("current_step" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_step"] = "";
        }
        if (!("vm_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vm_name"] = "";
        }
        if (!("resource_group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource_group"] = "";
        }
        if (!("public_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_ip"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["started_at"] = null;
        }
        if (!("completed_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["completed_at"] = null;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeploymentStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentStatus(/** @type {Partial<DeploymentStatus>} */($$parsedSource));
    }
}

export class EntityItems {
    /**
     * Creates a new EntityItems instance.
     * @param {Partial<EntityItems>} [$$source = {}] - The source object to create the EntityItems.
     */
    constructor($$source = {}) {
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["tasks"] = [];
        }
        if (!("entities" in $$source)) {
            /**
             * @member
             * @type {models$0.Entity[]}
             */
            this["entities"] = [];
        }
        if (!("untracked_tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedTask[]}
             */
            this["untracked_tasks"] = [];
        }
        if (!("untracked_entities" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedEntity[]}
             */
            this["untracked_entities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntityItems instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntityItems}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField1_0($$parsedSource["entities"]);
        }
        if ("untracked_tasks" in $$parsedSource) {
            $$parsedSource["untracked_tasks"] = $$createField2_0($$parsedSource["untracked_tasks"]);
        }
        if ("untracked_entities" in $$parsedSource) {
            $$parsedSource["untracked_entities"] = $$createField3_0($$parsedSource["untracked_entities"]);
        }
        return new EntityItems(/** @type {Partial<EntityItems>} */($$parsedSource));
    }
}

export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("formattedSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["formattedSize"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

export class Gender {
    /**
     * Creates a new Gender instance.
     * @param {Partial<Gender>} [$$source = {}] - The source object to create the Gender.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Gender instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Gender}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Gender(/** @type {Partial<Gender>} */($$parsedSource));
    }
}

export class ImportItems {
    /**
     * Creates a new ImportItems instance.
     * @param {Partial<ImportItems>} [$$source = {}] - The source object to create the ImportItems.
     */
    constructor($$source = {}) {
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["tasks"] = [];
        }
        if (!("entities" in $$source)) {
            /**
             * @member
             * @type {models$0.Entity[]}
             */
            this["entities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportItems instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportItems}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField1_0($$parsedSource["entities"]);
        }
        return new ImportItems(/** @type {Partial<ImportItems>} */($$parsedSource));
    }
}

export class ItemsForCheckpoint {
    /**
     * Creates a new ItemsForCheckpoint instance.
     * @param {Partial<ItemsForCheckpoint>} [$$source = {}] - The source object to create the ItemsForCheckpoint.
     */
    constructor($$source = {}) {
        if (!("modified_tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.Task[]}
             */
            this["modified_tasks"] = [];
        }
        if (!("untracked_files" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedTask[]}
             */
            this["untracked_files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemsForCheckpoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ItemsForCheckpoint}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified_tasks" in $$parsedSource) {
            $$parsedSource["modified_tasks"] = $$createField0_0($$parsedSource["modified_tasks"]);
        }
        if ("untracked_files" in $$parsedSource) {
            $$parsedSource["untracked_files"] = $$createField1_0($$parsedSource["untracked_files"]);
        }
        return new ItemsForCheckpoint(/** @type {Partial<ItemsForCheckpoint>} */($$parsedSource));
    }
}

/**
 * NullString represents a nullable string from the database
 */
export class NullString {
    /**
     * Creates a new NullString instance.
     * @param {Partial<NullString>} [$$source = {}] - The source object to create the NullString.
     */
    constructor($$source = {}) {
        if (!("Valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Valid"] = false;
        }
        if (!("String" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["String"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NullString instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NullString}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NullString(/** @type {Partial<NullString>} */($$parsedSource));
    }
}

export class ProfileUpdateData {
    /**
     * Creates a new ProfileUpdateData instance.
     * @param {Partial<ProfileUpdateData>} [$$source = {}] - The source object to create the ProfileUpdateData.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["first_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["email"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bio"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["location"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["country_id"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["gender_id"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["artstation_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["behance_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["instagram_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["x_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["linkedin_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["github_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["portfolio_link"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reel_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["job_title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["company"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["years_experience"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["hourly_rate"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["availability"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["profile_visibility"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileUpdateData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileUpdateData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileUpdateData(/** @type {Partial<ProfileUpdateData>} */($$parsedSource));
    }
}

export class RecycleItem {
    /**
     * Creates a new RecycleItem instance.
     * @param {Partial<RecycleItem>} [$$source = {}] - The source object to create the RecycleItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parent_id"] = "";
        }
        if (!("parent_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parent_name"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecycleItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecycleItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecycleItem(/** @type {Partial<RecycleItem>} */($$parsedSource));
    }
}

export class Skill {
    /**
     * Creates a new Skill instance.
     * @param {Partial<Skill>} [$$source = {}] - The source object to create the Skill.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Skill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill(/** @type {Partial<Skill>} */($$parsedSource));
    }
}

export class SkillData {
    /**
     * Creates a new SkillData instance.
     * @param {Partial<SkillData>} [$$source = {}] - The source object to create the SkillData.
     */
    constructor($$source = {}) {
        if (!("skill_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skill_id"] = "";
        }
        if (!("proficiency_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proficiency_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillData(/** @type {Partial<SkillData>} */($$parsedSource));
    }
}

export class Tool {
    /**
     * Creates a new Tool instance.
     * @param {Partial<Tool>} [$$source = {}] - The source object to create the Tool.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tool}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tool(/** @type {Partial<Tool>} */($$parsedSource));
    }
}

export class ToolData {
    /**
     * Creates a new ToolData instance.
     * @param {Partial<ToolData>} [$$source = {}] - The source object to create the ToolData.
     */
    constructor($$source = {}) {
        if (!("tool_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_id"] = "";
        }
        if (!("proficiency_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proficiency_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolData(/** @type {Partial<ToolData>} */($$parsedSource));
    }
}

export class UntrackedItems {
    /**
     * Creates a new UntrackedItems instance.
     * @param {Partial<UntrackedItems>} [$$source = {}] - The source object to create the UntrackedItems.
     */
    constructor($$source = {}) {
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedTask[]}
             */
            this["tasks"] = [];
        }
        if (!("entities" in $$source)) {
            /**
             * @member
             * @type {models$0.UntrackedEntity[]}
             */
            this["entities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UntrackedItems instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UntrackedItems}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField1_0($$parsedSource["entities"]);
        }
        return new UntrackedItems(/** @type {Partial<UntrackedItems>} */($$parsedSource));
    }
}

/**
 * Profile response types
 */
export class UserProfile {
    /**
     * Creates a new UserProfile instance.
     * @param {Partial<UserProfile>} [$$source = {}] - The source object to create the UserProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Basic info
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("first_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["first_name"] = "";
        }
        if (!("last_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_name"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("photo" in $$source)) {
            /**
             * Can be []byte or string
             * @member
             * @type {any}
             */
            this["photo"] = null;
        }
        if (!("bio" in $$source)) {
            /**
             * Extended profile
             * @member
             * @type {string}
             */
            this["bio"] = "";
        }
        if (!("location" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["location"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NullString | null | undefined}
             */
            this["country_id"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NullString | null | undefined}
             */
            this["gender_id"] = null;
        }
        if (!("date_of_birth" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date_of_birth"] = "";
        }
        if (!("availability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availability"] = "";
        }
        if (!("profile_visibility" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile_visibility"] = "";
        }
        if (!("job_title" in $$source)) {
            /**
             * Professional info
             * @member
             * @type {string}
             */
            this["job_title"] = "";
        }
        if (!("company" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["company"] = "";
        }
        if (!("years_experience" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["years_experience"] = 0;
        }
        if (!("hourly_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hourly_rate"] = 0;
        }
        if (!("artstation_link" in $$source)) {
            /**
             * Individual link fields from backend
             * @member
             * @type {string}
             */
            this["artstation_link"] = "";
        }
        if (!("behance_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["behance_link"] = "";
        }
        if (!("instagram_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instagram_link"] = "";
        }
        if (!("x_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["x_link"] = "";
        }
        if (!("linkedin_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["linkedin_link"] = "";
        }
        if (!("github_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["github_link"] = "";
        }
        if (!("portfolio_link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["portfolio_link"] = "";
        }
        if (!("reel_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reel_url"] = "";
        }
        if (!("tools" in $$source)) {
            /**
             * Collections
             * @member
             * @type {UserTool[]}
             */
            this["tools"] = [];
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {UserSkill[]}
             */
            this["skills"] = [];
        }
        if (!("studios" in $$source)) {
            /**
             * @member
             * @type {UserStudio[]}
             */
            this["studios"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserProfile}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType7;
        const $$createField25_0 = $$createType9;
        const $$createField26_0 = $$createType11;
        const $$createField27_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("country_id" in $$parsedSource) {
            $$parsedSource["country_id"] = $$createField8_0($$parsedSource["country_id"]);
        }
        if ("gender_id" in $$parsedSource) {
            $$parsedSource["gender_id"] = $$createField9_0($$parsedSource["gender_id"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField25_0($$parsedSource["tools"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField26_0($$parsedSource["skills"]);
        }
        if ("studios" in $$parsedSource) {
            $$parsedSource["studios"] = $$createField27_0($$parsedSource["studios"]);
        }
        return new UserProfile(/** @type {Partial<UserProfile>} */($$parsedSource));
    }
}

export class UserSkill {
    /**
     * Creates a new UserSkill instance.
     * @param {Partial<UserSkill>} [$$source = {}] - The source object to create the UserSkill.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("skill_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skill_id"] = "";
        }
        if (!("skill_name" in $$source)) {
            /**
             * Backend returns skill_name
             * @member
             * @type {string}
             */
            this["skill_name"] = "";
        }
        if (!("skill_category" in $$source)) {
            /**
             * Backend returns skill_category
             * @member
             * @type {string}
             */
            this["skill_category"] = "";
        }
        if (!("proficiency_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proficiency_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSkill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserSkill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSkill(/** @type {Partial<UserSkill>} */($$parsedSource));
    }
}

export class UserStudio {
    /**
     * Creates a new UserStudio instance.
     * @param {Partial<UserStudio>} [$$source = {}] - The source object to create the UserStudio.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserStudio instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserStudio}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserStudio(/** @type {Partial<UserStudio>} */($$parsedSource));
    }
}

export class UserTool {
    /**
     * Creates a new UserTool instance.
     * @param {Partial<UserTool>} [$$source = {}] - The source object to create the UserTool.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tool_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_id"] = "";
        }
        if (!("tool_name" in $$source)) {
            /**
             * Backend returns tool_name
             * @member
             * @type {string}
             */
            this["tool_name"] = "";
        }
        if (!("tool_category" in $$source)) {
            /**
             * Backend returns tool_category
             * @member
             * @type {string}
             */
            this["tool_category"] = "";
        }
        if (!("proficiency_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proficiency_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserTool instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserTool}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserTool(/** @type {Partial<UserTool>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AssetStateItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = NullString.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = UserTool.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = UserSkill.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = UserStudio.createFrom;
const $$createType13 = $Create.Array($$createType12);
