// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repository$0 from "../internal/repository/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @param {string} email
 * @param {string} roleName
 * @returns {$CancellablePromise<models$0.User>}
 */
export function AddUser(projectPath, email, roleName) {
    return $Call.ByID(3138298450, projectPath, email, roleName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddUserSynced adds a user to the local project and marks them as synced.
 * Used when the server already has the user data via its collaborator endpoint.
 * @param {string} projectPath
 * @param {string} email
 * @param {string} roleName
 * @returns {$CancellablePromise<models$0.User>}
 */
export function AddUserSynced(projectPath, email, roleName) {
    return $Call.ByID(3539129760, projectPath, email, roleName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} templateName
 * @returns {$CancellablePromise<void>}
 */
export function ApplyTemplate(projectPath, templateName) {
    return $Call.ByID(634171424, projectPath, templateName);
}

/**
 * @param {string} projectPath
 * @param {string} userId
 * @param {string} roleName
 * @returns {$CancellablePromise<void>}
 */
export function ChangeRole(projectPath, userId, roleName) {
    return $Call.ByID(810773794, projectPath, userId, roleName);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function CloseProject(projectPath) {
    return $Call.ByID(114032371, projectPath);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @param {string} workingDir
 * @param {string} templateName
 * @param {string} hostingMode
 * @param {string} studioId
 * @returns {$CancellablePromise<repository$0.ProjectInfo>}
 */
export function CreateProject(projectUri, studioName, workingDir, templateName, hostingMode, studioId) {
    return $Call.ByID(914775891, projectUri, studioName, workingDir, templateName, hostingMode, studioId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteRemoteProject permanently deletes a project from the studio server.
 * This requires admin permissions and cannot be undone.
 * @param {string} projectUri
 * @param {string} studioName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRemoteProject(projectUri, studioName) {
    return $Call.ByID(1336252116, projectUri, studioName);
}

/**
 * @param {string} projectWorkingDir
 * @param {string} directory
 * @param {string[]} ignoreList
 * @param {string[]} tracked
 * @returns {$CancellablePromise<$models.UntrackedItems>}
 */
export function GetFolderUntrackedItems(projectWorkingDir, directory, ignoreList, tracked) {
    return $Call.ByID(83768171, projectWorkingDir, directory, ignoreList, tracked).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetIgnoreList(projectPath) {
    return $Call.ByID(880721004, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<boolean>}
 */
export function GetIsClose(projectPath) {
    return $Call.ByID(1046148786, projectPath);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function GetPreview(projectPath) {
    return $Call.ByID(4275126350, projectPath);
}

/**
 * @param {string} url
 * @param {string} name
 * @param {string} hostingMode
 * @param {string} studioId
 * @returns {$CancellablePromise<repository$0.ProjectInfo[]>}
 */
export function GetStudioProjects(url, name, hostingMode, studioId) {
    return $Call.ByID(155248386, url, name, hostingMode, studioId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectUri
 * @returns {$CancellablePromise<string>}
 */
export function GetSyncToken(projectUri) {
    return $Call.ByID(2014393022, projectUri);
}

/**
 * @returns {$CancellablePromise<repository$0.ProjectInfo[]>}
 */
export function GetTemplates() {
    return $Call.ByID(2590730853).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * InspectClusttaFile opens a .clst file and extracts its metadata.
 * If the file is outside Clustta's known project directories, updates the
 * working directory in the database to a sibling folder of the .clst file.
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.ClusttaFileInfo>}
 */
export function InspectClusttaFile(filePath) {
    return $Call.ByID(1688002974, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} itemPath
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<boolean>}
 */
export function IsIgnored(itemPath, ignoreList) {
    return $Call.ByID(2693616968, itemPath, ignoreList);
}

/**
 * LeaveProject removes the current user as a collaborator from a remote project.
 * The project remote URL is used to construct the leave endpoint.
 * @param {string} remoteUrl
 * @returns {$CancellablePromise<void>}
 */
export function LeaveProject(remoteUrl) {
    return $Call.ByID(595831886, remoteUrl);
}

/**
 * MakeProjectRemote uploads a local project to Clustta Cloud as a remote project.
 * Creates the remote project, remaps IDs to match remote, pushes all data, and stores the remote URL locally.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function MakeProjectRemote(projectPath) {
    return $Call.ByID(3213267975, projectPath);
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<repository$0.ProjectInfo>}
 */
export function ProjectInfo(projectPath) {
    return $Call.ByID(1383457795, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string[]} projectPaths
 * @returns {$CancellablePromise<repository$0.ProjectInfo[]>}
 */
export function ProjectsInfo(projectPaths) {
    return $Call.ByID(686940384, projectPaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function Purge(projectPath) {
    return $Call.ByID(2913987721, projectPath);
}

/**
 * RemoveProjectFromRemote deletes the remote copy and clears the local remote URL.
 * The local project data is preserved.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProjectFromRemote(projectPath) {
    return $Call.ByID(3939292029, projectPath);
}

/**
 * @param {string} projectPath
 * @param {string} userId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveUser(projectPath, userId) {
    return $Call.ByID(4241326069, projectPath, userId);
}

/**
 * RemoveUserSynced removes a user from the local project and marks the tomb as synced.
 * Used when the server already has the deletion via its own endpoint.
 * @param {string} projectPath
 * @param {string} userId
 * @returns {$CancellablePromise<void>}
 */
export function RemoveUserSynced(projectPath, userId) {
    return $Call.ByID(3362070715, projectPath, userId);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function Rename(projectUri, studioName, newName) {
    return $Call.ByID(4132178576, projectUri, studioName, newName);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetDefaultTemplates() {
    return $Call.ByID(2733819533);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @param {string[]} ignoreList
 * @returns {$CancellablePromise<void>}
 */
export function SetIgnoreList(projectUri, studioName, ignoreList) {
    return $Call.ByID(610021480, projectUri, studioName, ignoreList);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @returns {$CancellablePromise<void>}
 */
export function ToggleCloseProject(projectUri, studioName) {
    return $Call.ByID(2004355099, projectUri, studioName);
}

/**
 * TrimProject removes all chunks and previews from the project database to reduce file size.
 * The data can be re-fetched from the remote when needed.
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function TrimProject(projectPath) {
    return $Call.ByID(2900900023, projectPath);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @param {string} iconValue
 * @returns {$CancellablePromise<void>}
 */
export function UpdateIcon(projectUri, studioName, iconValue) {
    return $Call.ByID(3756813102, projectUri, studioName, iconValue);
}

/**
 * @param {string} projectPath
 * @param {string} previewPath
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePreview(projectPath, previewPath) {
    return $Call.ByID(1284912265, projectPath, previewPath);
}

/**
 * @param {string} projectUri
 * @param {string} studioName
 * @param {string} newWorkingDir
 * @returns {$CancellablePromise<void>}
 */
export function UpdateWorkingDirectory(projectUri, studioName, newWorkingDir) {
    return $Call.ByID(3745129021, projectUri, studioName, newWorkingDir);
}

/**
 * UploadProject uploads a local .clst project to a remote studio.
 * It creates the project on the remote, copies the file, remaps IDs, and prepares for sync.
 * For cloud-hosted studios, set hostingMode to "cloud" and provide the studioId.
 * @param {string} sourceClstPath
 * @param {string} studioName
 * @param {string} workingDir
 * @param {string} projectName
 * @param {string} remoteProjectUrl
 * @param {string} hostingMode
 * @param {string} studioId
 * @returns {$CancellablePromise<repository$0.ProjectInfo>}
 */
export function UploadProject(sourceClstPath, studioName, workingDir, projectName, remoteProjectUrl, hostingMode, studioId) {
    return $Call.ByID(3550877976, sourceClstPath, studioName, workingDir, projectName, remoteProjectUrl, hostingMode, studioId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} userId
 * @returns {$CancellablePromise<boolean>}
 */
export function UserInProject(projectPath, userId) {
    return $Call.ByID(3209082523, projectPath, userId);
}

/**
 * ValidateProjectFile checks if a .clst file is a valid Clustta project.
 * Returns true if the file is valid, false otherwise.
 * @param {string} filePath
 * @returns {$CancellablePromise<boolean>}
 */
export function ValidateProjectFile(filePath) {
    return $Call.ByID(4035322203, filePath);
}

// Private type creation functions
const $$createType0 = models$0.User.createFrom;
const $$createType1 = repository$0.ProjectInfo.createFrom;
const $$createType2 = $models.UntrackedItems.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $models.ClusttaFileInfo.createFrom;
