// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../internal/settings/models.js";

/**
 * AddDependencyPreset adds a dependency preset to a project.
 * @param {string} projectId
 * @param {any} presetData
 * @returns {$CancellablePromise<void>}
 */
export function AddDependencyPreset(projectId, presetData) {
    return $Call.ByID(278533171, projectId, presetData);
}

/**
 * AddProjectLocation adds a new project location with name and path.
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<settings$0.ProjectLocation>}
 */
export function AddProjectLocation(name, path) {
    return $Call.ByID(576088381, name, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddProjectWorkspace adds a workspace configuration to a project.
 * @param {string} projectId
 * @param {any} workspaceData
 * @returns {$CancellablePromise<void>}
 */
export function AddProjectWorkspace(projectId, workspaceData) {
    return $Call.ByID(4073366007, projectId, workspaceData);
}

/**
 * AddRecentProject adds a project to the recent projects list.
 * @param {string} studioName
 * @param {string} projectId
 * @returns {$CancellablePromise<string[]>}
 */
export function AddRecentProject(studioName, projectId) {
    return $Call.ByID(762029095, studioName, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AssignProjectToLocation assigns a project to a specific location.
 * @param {string} projectID
 * @param {string} locationID
 * @returns {$CancellablePromise<void>}
 */
export function AssignProjectToLocation(projectID, locationID) {
    return $Call.ByID(3752105278, projectID, locationID);
}

/**
 * CanDeleteLocation checks if a location can be safely deleted.
 * @param {string} locationID
 * @returns {$CancellablePromise<boolean>}
 */
export function CanDeleteLocation(locationID) {
    return $Call.ByID(3404860008, locationID);
}

/**
 * CheckAllLocationsHealth verifies the health status of all project locations.
 * @returns {$CancellablePromise<settings$0.LocationHealth[]>}
 */
export function CheckAllLocationsHealth() {
    return $Call.ByID(862862689).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckLocationHealth verifies the health status of a specific location.
 * @param {string} locationID
 * @returns {$CancellablePromise<settings$0.LocationHealth>}
 */
export function CheckLocationHealth(locationID) {
    return $Call.ByID(2048849247, locationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ClearRecentProject clears the recent projects list for the specified studio.
 * @param {string} studioName
 * @returns {$CancellablePromise<void>}
 */
export function ClearRecentProject(studioName) {
    return $Call.ByID(2255147105, studioName);
}

/**
 * DeleteIntegrationCredential deletes integration credentials for an integration.
 * @param {string} integrationId
 * @returns {$CancellablePromise<void>}
 */
export function DeleteIntegrationCredential(integrationId) {
    return $Call.ByID(2497484404, integrationId);
}

/**
 * GetAllLocationPaths retrieves all configured project locations.
 * @returns {$CancellablePromise<settings$0.ProjectLocation[]>}
 */
export function GetAllLocationPaths() {
    return $Call.ByID(1879856430).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetBridgeEnabled returns whether the bridge HTTP server is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetBridgeEnabled() {
    return $Call.ByID(406544000);
}

/**
 * GetCurrentVersion retrieves the current application version number.
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(2344331797);
}

/**
 * GetDefaultLocation retrieves the default project location.
 * @returns {$CancellablePromise<settings$0.ProjectLocation>}
 */
export function GetDefaultLocation() {
    return $Call.ByID(904599504).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDefaultViewMode retrieves the default view mode setting.
 * Returns "compact" (list), "dense" (compact), or "grid".
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultViewMode() {
    return $Call.ByID(1115855849);
}

/**
 * GetEulaAccepted retrieves whether the user has accepted the EULA.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetEulaAccepted() {
    return $Call.ByID(3424798202);
}

/**
 * GetIconScheme retrieves the current icon scheme name.
 * @returns {$CancellablePromise<string>}
 */
export function GetIconScheme() {
    return $Call.ByID(636356804);
}

/**
 * GetIntegrationCredential retrieves integration credentials for an integration.
 * Credentials are stored per user per integration (not per project).
 * @param {string} integrationId
 * @returns {$CancellablePromise<settings$0.IntegrationCredential>}
 */
export function GetIntegrationCredential(integrationId) {
    return $Call.ByID(3906565165, integrationId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLanguage retrieves the user's language preference.
 * @returns {$CancellablePromise<string>}
 */
export function GetLanguage() {
    return $Call.ByID(2844941544);
}

/**
 * GetLastStudio retrieves the last active studio name.
 * @returns {$CancellablePromise<string>}
 */
export function GetLastStudio() {
    return $Call.ByID(1532016140);
}

/**
 * GetLocationUsage returns the number of projects using a location.
 * @param {string} locationID
 * @returns {$CancellablePromise<number>}
 */
export function GetLocationUsage(locationID) {
    return $Call.ByID(435118172, locationID);
}

/**
 * GetLogContents reads and returns the last N lines from the log file.
 * @param {number} maxLines
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogContents(maxLines) {
    return $Call.ByID(244600402, maxLines).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLogPath returns the path to the Clustta log file.
 * @returns {$CancellablePromise<string>}
 */
export function GetLogPath() {
    return $Call.ByID(1658969463);
}

/**
 * GetMinimizeOnClose returns whether the app minimizes to tray on close.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetMinimizeOnClose() {
    return $Call.ByID(319830377);
}

/**
 * GetPinnedProjects retrieves all pinned projects for the specified studio.
 * @param {string} studioName
 * @returns {$CancellablePromise<string[]>}
 */
export function GetPinnedProjects(studioName) {
    return $Call.ByID(13254414, studioName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetProjectDependencyPresets retrieves all dependency presets for a project.
 * @param {string} projectId
 * @returns {$CancellablePromise<any[]>}
 */
export function GetProjectDependencyPresets(projectId) {
    return $Call.ByID(3058392474, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetProjectDirectory retrieves the default project directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetProjectDirectory() {
    return $Call.ByID(119555146);
}

/**
 * GetProjectLocation retrieves the location ID for a specific project.
 * @param {string} projectID
 * @returns {$CancellablePromise<string>}
 */
export function GetProjectLocation(projectID) {
    return $Call.ByID(3483756876, projectID);
}

/**
 * GetProjectWorkspaces retrieves all workspace configurations for a project.
 * @param {string} projectId
 * @returns {$CancellablePromise<any[]>}
 */
export function GetProjectWorkspaces(projectId) {
    return $Call.ByID(2164081225, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetRecentProjects retrieves recently accessed projects for the specified studio.
 * @param {string} studioName
 * @returns {$CancellablePromise<string[]>}
 */
export function GetRecentProjects(studioName) {
    return $Call.ByID(2190435435, studioName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSharedProjectDirectory retrieves the shared project directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetSharedProjectDirectory() {
    return $Call.ByID(952704375);
}

/**
 * GetShowTypeIcons returns whether type icons are shown in the browser.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetShowTypeIcons() {
    return $Call.ByID(742250271);
}

/**
 * GetStudios retrieves all configured studios from user settings.
 * @param {string} path
 * @returns {$CancellablePromise<settings$0.Studio[]>}
 */
export function GetStudios(path) {
    return $Call.ByID(2852753313, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetSyncAfterCheckpoint returns whether auto-sync after checkpoint is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSyncAfterCheckpoint() {
    return $Call.ByID(1410419631);
}

/**
 * GetTheme retrieves the current theme name.
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(3632431035);
}

/**
 * GetUseGrid retrieves whether grid view is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetUseGrid() {
    return $Call.ByID(3478254425);
}

/**
 * GetUserDirectory returns the current user's home directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetUserDirectory() {
    return $Call.ByID(3623047360);
}

/**
 * GetUsername returns the current system username.
 * @returns {$CancellablePromise<string>}
 */
export function GetUsername() {
    return $Call.ByID(50562878);
}

/**
 * GetWorkingDirectory retrieves the working directory path.
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkingDirectory() {
    return $Call.ByID(1696233652);
}

/**
 * IsProjectGridView returns whether project grid view is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsProjectGridView() {
    return $Call.ByID(809995474);
}

/**
 * IsShowUntrackedProjects returns whether untracked projects are visible.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsShowUntrackedProjects() {
    return $Call.ByID(2237864900);
}

/**
 * PinProject pins a project to the studio's favorites list.
 * @param {string} studioName
 * @param {string} projectId
 * @returns {$CancellablePromise<string[]>}
 */
export function PinProject(studioName, projectId) {
    return $Call.ByID(2392329694, studioName, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RemoveDependencyPreset removes a dependency preset from a project.
 * @param {string} projectId
 * @param {string} presetName
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDependencyPreset(projectId, presetName) {
    return $Call.ByID(1574357336, projectId, presetName);
}

/**
 * RemoveProjectLocation removes a project location by ID.
 * @param {string} locationID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProjectLocation(locationID) {
    return $Call.ByID(3992887900, locationID);
}

/**
 * RemoveProjectWorkspace removes a workspace configuration from a project.
 * @param {string} projectId
 * @param {string} workspaceName
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProjectWorkspace(projectId, workspaceName) {
    return $Call.ByID(2360960656, projectId, workspaceName);
}

/**
 * SaveIntegrationCredential saves or updates integration credentials.
 * Credentials are stored per user per integration (not per project).
 * @param {settings$0.IntegrationCredential} cred
 * @returns {$CancellablePromise<void>}
 */
export function SaveIntegrationCredential(cred) {
    return $Call.ByID(927307362, cred);
}

/**
 * SetBridgeEnabled sets the bridge HTTP server enabled preference.
 * Starts or stops the bridge server accordingly.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetBridgeEnabled(enabled) {
    return $Call.ByID(2597264452, enabled);
}

/**
 * SetCurrentVersion sets the current application version number.
 * @param {string} versionNumber
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentVersion(versionNumber) {
    return $Call.ByID(3579646225, versionNumber);
}

/**
 * SetDefaultLocation sets the default project location by ID.
 * @param {string} locationID
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultLocation(locationID) {
    return $Call.ByID(1651704380, locationID);
}

/**
 * SetDefaultViewMode sets the default view mode.
 * @param {string} viewMode
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultViewMode(viewMode) {
    return $Call.ByID(204045845, viewMode);
}

/**
 * SetEulaAccepted sets the EULA acceptance status.
 * @param {boolean} eulaAccepted
 * @returns {$CancellablePromise<void>}
 */
export function SetEulaAccepted(eulaAccepted) {
    return $Call.ByID(3565249198, eulaAccepted);
}

/**
 * SetIconScheme sets the icon scheme for the application.
 * @param {string} iconScheme
 * @returns {$CancellablePromise<void>}
 */
export function SetIconScheme(iconScheme) {
    return $Call.ByID(2125293608, iconScheme);
}

/**
 * SetLanguage sets the user's language preference.
 * @param {string} language
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(language) {
    return $Call.ByID(2588646004, language);
}

/**
 * SetLastStudio sets the last active studio name.
 * @param {string} lastStudioName
 * @returns {$CancellablePromise<void>}
 */
export function SetLastStudio(lastStudioName) {
    return $Call.ByID(4086447016, lastStudioName);
}

/**
 * SetMinimizeOnClose sets the minimize-to-tray on close preference.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetMinimizeOnClose(enabled) {
    return $Call.ByID(2305241605, enabled);
}

/**
 * SetProjectDirectory sets the default project directory path.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetProjectDirectory(dir) {
    return $Call.ByID(3694495326, dir);
}

/**
 * SetSharedProjectDirectory sets the shared project directory path.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetSharedProjectDirectory(dir) {
    return $Call.ByID(2608064267, dir);
}

/**
 * SetShowTypeIcons sets the show type icons preference.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetShowTypeIcons(enabled) {
    return $Call.ByID(3308454819, enabled);
}

/**
 * SetSyncAfterCheckpoint sets the auto-sync after checkpoint preference.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSyncAfterCheckpoint(enabled) {
    return $Call.ByID(1067699379, enabled);
}

/**
 * SetTheme sets the application theme.
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(694474447, theme);
}

/**
 * SetUseGrid sets whether to use grid view.
 * @param {boolean} useGrid
 * @returns {$CancellablePromise<void>}
 */
export function SetUseGrid(useGrid) {
    return $Call.ByID(733610941, useGrid);
}

/**
 * SetWorkingDirectory sets the working directory path.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkingDirectory(dir) {
    return $Call.ByID(2466292864, dir);
}

/**
 * ToggleProjectGridView toggles between grid and list view for projects.
 * @returns {$CancellablePromise<void>}
 */
export function ToggleProjectGridView() {
    return $Call.ByID(1335955422);
}

/**
 * ToggleShowUntrackedProjects toggles visibility of untracked projects.
 * @returns {$CancellablePromise<void>}
 */
export function ToggleShowUntrackedProjects() {
    return $Call.ByID(389465744);
}

/**
 * UnpinProject removes a project from the studio's favorites list.
 * @param {string} studioName
 * @param {string} projectId
 * @returns {$CancellablePromise<string[]>}
 */
export function UnpinProject(studioName, projectId) {
    return $Call.ByID(3096272593, studioName, projectId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpdateDependencyPreset updates an existing dependency preset.
 * @param {string} projectId
 * @param {string} presetName
 * @param {any} updatedPreset
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDependencyPreset(projectId, presetName, updatedPreset) {
    return $Call.ByID(3275376729, projectId, presetName, updatedPreset);
}

/**
 * UpdateProjectLocation updates a project location's name and path.
 * @param {string} locationID
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProjectLocation(locationID, name, path) {
    return $Call.ByID(1079821971, locationID, name, path);
}

// Private type creation functions
const $$createType0 = settings$0.ProjectLocation.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = settings$0.LocationHealth.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = settings$0.IntegrationCredential.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = settings$0.Studio.createFrom;
const $$createType8 = $Create.Array($$createType7);
