// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateShareLink creates a shareable download link for one or more checkpoints.
 * The studioUrl should be the resolved studio server URL (e.g. "http://studio.example.com").
 * The projectName should be the project identifier (without .clst extension).
 * @param {string} studioUrl
 * @param {string} projectName
 * @param {string[]} checkpointIds
 * @param {string} label
 * @param {number} expiresInHours
 * @returns {$CancellablePromise<$models.ShareLinkResponse>}
 */
export function CreateShareLink(studioUrl, projectName, checkpointIds, label, expiresInHours) {
    return $Call.ByID(2035526811, studioUrl, projectName, checkpointIds, label, expiresInHours).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ShareLinkResponse.createFrom;
