// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * Changes the file path associated with an existing template
 * @param {string} projectPath
 * @param {string} templateName
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ChangeTemplateFile(projectPath, templateName, filePath) {
    return $Call.ByID(391432429, projectPath, templateName, filePath);
}

/**
 * Creates a new template with name and file path
 * @param {string} projectPath
 * @param {string} templateName
 * @param {string} filePath
 * @returns {$CancellablePromise<models$0.Template>}
 */
export function CreateTemplate(projectPath, templateName, filePath) {
    return $Call.ByID(3156130547, projectPath, templateName, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Deletes a template by name from the project database
 * @param {string} projectPath
 * @param {string} templateName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTemplate(projectPath, templateName) {
    return $Call.ByID(1952849308, projectPath, templateName);
}

/**
 * Retrieves a single template by ID from the project database
 * @param {string} projectPath
 * @param {string} templateId
 * @returns {$CancellablePromise<models$0.Template>}
 */
export function GetTemplate(projectPath, templateId) {
    return $Call.ByID(1175489573, projectPath, templateId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Retrieves all templates from the project database
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Template[]>}
 */
export function GetTemplates(projectPath) {
    return $Call.ByID(2718755682, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Renames an existing template in the project database
 * @param {string} projectPath
 * @param {string} templateName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTemplate(projectPath, templateName, newName) {
    return $Call.ByID(2409633105, projectPath, templateName, newName);
}

// Private type creation functions
const $$createType0 = models$0.Template.createFrom;
const $$createType1 = $Create.Array($$createType0);
