// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} projectPath
 * @returns {Promise<$models.RecycleItem[]> & { cancel(): void }}
 */
export function GetTrashs(projectPath) {
    let $resultPromise = /** @type {any} */($Call.ByID(2486332128, projectPath));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} projectPath
 * @param {string} id
 * @param {string} itemType
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Restore(projectPath, id, itemType) {
    let $resultPromise = /** @type {any} */($Call.ByID(2353219489, projectPath, id, itemType));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.RecycleItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
