// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Retrieves all deleted items from project database including entities, templates, tasks, and checkpoints
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.RecycleItem[]>}
 */
export function GetTrashs(projectPath) {
    return $Call.ByID(2486332128, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Restores a deleted item by ID and type from the recycle bin
 * @param {string} projectPath
 * @param {string} id
 * @param {string} itemType
 * @returns {$CancellablePromise<void>}
 */
export function Restore(projectPath, id, itemType) {
    return $Call.ByID(2353219489, projectPath, id, itemType);
}

// Private type creation functions
const $$createType0 = $models.RecycleItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
