// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * Creates a new role with name and permission attributes
 * @param {string} projectPath
 * @param {string} name
 * @param {models$0.RoleAttributes} attributes
 * @returns {$CancellablePromise<models$0.Role>}
 */
export function AddRole(projectPath, name, attributes) {
    return $Call.ByID(1510146311, projectPath, name, attributes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Deletes a role by ID from the project database
 * @param {string} projectPath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRole(projectPath, id) {
    return $Call.ByID(1732439423, projectPath, id);
}

/**
 * Fetches user data from remote authentication service by ID
 * @param {string} userId
 * @returns {$CancellablePromise<models$0.User>}
 */
export function FetchUserById(userId) {
    return $Call.ByID(2104969195, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Retrieves all roles from the project database
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Role[]>}
 */
export function GetRoles(projectPath) {
    return $Call.ByID(1185149717, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Retrieves a single user by ID from the project database
 * @param {string} projectPath
 * @param {string} userId
 * @returns {$CancellablePromise<models$0.User>}
 */
export function GetUser(projectPath, userId) {
    return $Call.ByID(2223938271, projectPath, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Retrieves all users from the project database
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.User[]>}
 */
export function GetUsers(projectPath) {
    return $Call.ByID(1484618948, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Updates an existing role's name and permission attributes
 * @param {string} projectPath
 * @param {string} id
 * @param {string} name
 * @param {models$0.RoleAttributes} attributes
 * @returns {$CancellablePromise<models$0.Role>}
 */
export function UpdateRole(projectPath, id, name, attributes) {
    return $Call.ByID(894761805, projectPath, id, name, attributes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Role.createFrom;
const $$createType1 = models$0.User.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Array($$createType1);
