// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../internal/repository/models/models.js";

/**
 * Adds a workflow to an collection with specified parent and type
 * @param {string} projectPath
 * @param {string} workflow_id
 * @param {string} name
 * @param {string} collectionTypeId
 * @param {string} parentId
 * @returns {$CancellablePromise<void>}
 */
export function AddWorkflow(projectPath, workflow_id, name, collectionTypeId, parentId) {
    return $Call.ByID(4015215456, projectPath, workflow_id, name, collectionTypeId, parentId);
}

/**
 * Creates a new workflow with assets, collections, and links
 * @param {string} projectPath
 * @param {string} name
 * @param {models$0.WorkflowAsset[]} workflowAssets
 * @param {models$0.WorkflowCollection[]} workflowCollections
 * @param {models$0.WorkflowLink[]} workflowLinks
 * @returns {$CancellablePromise<models$0.Workflow>}
 */
export function CreateWorkflow(projectPath, name, workflowAssets, workflowCollections, workflowLinks) {
    return $Call.ByID(4183453851, projectPath, name, workflowAssets, workflowCollections, workflowLinks).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Retrieves all workflows from the project database
 * @param {string} projectPath
 * @returns {$CancellablePromise<models$0.Workflow[]>}
 */
export function GetWorkflows(projectPath) {
    return $Call.ByID(1218687912, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Updates an existing workflow including assets, collections, and links
 * @param {string} projectPath
 * @param {string} workflowId
 * @param {string} name
 * @param {models$0.WorkflowAsset[]} workflowAssets
 * @param {models$0.WorkflowCollection[]} workflowCollections
 * @param {models$0.WorkflowLink[]} workflowLinks
 * @returns {$CancellablePromise<models$0.Workflow>}
 */
export function UpdateWorkflow(projectPath, workflowId, name, workflowAssets, workflowCollections, workflowLinks) {
    return $Call.ByID(871693934, projectPath, workflowId, name, workflowAssets, workflowCollections, workflowLinks).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Workflow.createFrom;
const $$createType1 = $Create.Array($$createType0);
