// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class StudioUserInfo {
    /**
     * Creates a new StudioUserInfo instance.
     * @param {Partial<StudioUserInfo>} [$$source = {}] - The source object to create the StudioUserInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("first_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["first_name"] = "";
        }
        if (!("last_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_name"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("role_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role_name"] = "";
        }
        if (!("studio_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_name"] = "";
        }
        if (!("studio_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_id"] = "";
        }
        if (!("role_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role_id"] = "";
        }
        if (!("photo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["photo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudioUserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StudioUserInfo}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("photo" in $$parsedSource) {
            $$parsedSource["photo"] = $$createField10_0($$parsedSource["photo"]);
        }
        return new StudioUserInfo(/** @type {Partial<StudioUserInfo>} */($$parsedSource));
    }
}
