// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config mirrors the public view returned by the central server.
 * Credentials are never included in this struct.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("integration_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["integration_id"] = "";
        }
        if (!("studio_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studio_id"] = "";
        }
        if (!("api_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_url"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("last_validated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_validated_at"] = 0;
        }
        if (!("last_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warning"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * CredentialsPayload is the shape accepted by save/test endpoints.
 */
export class CredentialsPayload {
    /**
     * Creates a new CredentialsPayload instance.
     * @param {Partial<CredentialsPayload>} [$$source = {}] - The source object to create the CredentialsPayload.
     */
    constructor($$source = {}) {
        if (!("api_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_url"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialsPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialsPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialsPayload(/** @type {Partial<CredentialsPayload>} */($$parsedSource));
    }
}
