// Auto-generated icon map for dynamic icon resolution
import {
  Ci3b,
  CiAep,
  CiAfdesign,
  CiAfphoto,
  CiAfpub,
  CiAi,
  CiAlert,
  CiAlphabets,
  CiAlphabetsAlt,
  CiArchive,
  CiArrowBackRamp,
  CiArrowBigUpLines,
  CiArrowDownOnSquareStack,
  CiArrowDownRamp,
  CiArrowDownRampAlert,
  CiArrowLeft,
  CiArrowLeftRamp,
  CiArrowUpRamp,
  CiArrowUpRampAlert,
  CiArrowsExpand,
  CiArrowsSort,
  CiBell,
  CiBezier,
  CiBlend,
  CiBone,
  CiBook,
  CiBookmark,
  CiBoxes,
  CiBrain,
  CiBrandArtstation,
  CiBrandBehance,
  CiBrandInstagram,
  CiBrandLinkedin,
  CiBrick,
  CiBrickCancel,
  CiBriefcase,
  CiBriefcaseCog,
  CiBriefcasePlus,
  CiBroom,
  CiBrush,
  CiBrushPlus,
  CiBug,
  CiBulb,
  CiC4d,
  CiCamera,
  CiCameraFlash,
  CiCanva,
  CiCdr,
  CiCharacterCreator,
  CiCheck,
  CiCheckCircle,
  CiCheckboxSelected,
  CiCheckboxSelectedActive,
  CiCheckboxUnselected,
  CiCheckpointStone,
  CiChevronDoubleLeft,
  CiChevronDown,
  CiChevronLeft,
  CiChevronRight,
  CiChevronUp,
  CiChproj,
  CiChrome,
  CiCircleCheck,
  CiCircleCheckAlert,
  CiCircleCheckGo,
  CiClapboard,
  CiClickup,
  CiClip,
  CiClipboard,
  CiClock,
  CiClose,
  CiCloseCircle,
  CiCloseWindow,
  CiCloudCancel,
  CiCloudCheck,
  CiCloudClock,
  CiCloudDown,
  CiCloudError,
  CiCloudSync,
  CiCloudUp,
  CiClustta,
  CiCodeBracket,
  CiCog,
  CiCollapseDown,
  CiCollapseLeft,
  CiCollapseRight,
  CiCollapseUp,
  CiCollapseWindow,
  CiCompass,
  CiConfirm,
  CiConsole,
  CiCopy,
  CiCpr,
  CiCreateSnapshot,
  CiCreditCard,
  CiCube,
  CiDataDownload,
  CiDataUpload,
  CiDatabaseSync,
  CiDefault,
  CiDependency,
  CiDependencyGraph2,
  CiDiamond,
  CiDigitalBinary,
  CiDotBig,
  CiDotBigAlert,
  CiDotBigDanger,
  CiDotSmall,
  CiDotSmallAlert,
  CiDots,
  CiDownload,
  CiDrive,
  CiDrum,
  CiDuplicate,
  CiEdit,
  CiExplorer,
  CiExplorerOpen,
  CiExtension,
  CiExtensionCancel,
  CiEye,
  CiEyeCancel,
  CiEyeCog,
  CiFacePlus,
  CiFigma,
  CiFile,
  CiFileName,
  CiFilePath,
  CiFilePlus,
  CiFileSearch,
  CiFileWatch,
  CiFileZip,
  CiFilmReel,
  CiFilmStrip,
  CiFilter,
  CiFire,
  CiFirefox,
  CiFla,
  CiFlash,
  CiFlashPlus,
  CiFloppyDisk,
  CiFlowChart,
  CiFlp,
  CiFolder,
  CiFolderArrowIn,
  CiFolderArrowUpRight,
  CiFolderGrid,
  CiFolderPlus,
  CiForwardSlash,
  CiFourSquares,
  CiFramer,
  CiGamepad,
  CiGeneric,
  CiGoogleDocs,
  CiGoogleDrive,
  CiHelp,
  CiHome,
  CiIclone,
  CiImage,
  CiImageCancel,
  CiImagePlus,
  CiIndd,
  CiInfo,
  CiInfoTriangle,
  CiJigsaw,
  CiKanban,
  CiKey,
  CiKitsu,
  CiKra,
  CiLamp,
  CiLaunch,
  CiLayers,
  CiLayersPlus,
  CiLayersPlusAlert,
  CiLayersPlusDanger,
  CiLibrary,
  CiLink,
  CiList,
  CiListCompact,
  CiListDown,
  CiLoading,
  CiLockClosed,
  CiLockOpen,
  CiLogin,
  CiLogout,
  CiLrcat,
  CiMa,
  CiMagnifyingGlass,
  CiMail,
  CiManRunning,
  CiMapPin,
  CiMasks,
  CiMax,
  CiMaximize,
  CiMaximizeWindow,
  CiMegaphone,
  CiMerge,
  CiMinimize,
  CiMinimizeWindow,
  CiMinusCircle,
  CiMiro,
  CiMonitor,
  CiMonitorPlus,
  CiMoon,
  CiMusic,
  CiMysteryBall,
  CiNewPin,
  CiNodeGraph,
  CiNotion,
  CiOpenBook,
  CiOverflow,
  CiPackage,
  CiPalette,
  CiPaperclip,
  CiParameters,
  CiPerson,
  CiPersonCircled,
  CiPersonMinus,
  CiPersonPlus,
  CiPersonSearch,
  CiPin,
  CiPlayPause,
  CiPlug,
  CiPlusCircle,
  CiPlusStone,
  CiPrinter,
  CiPrproj,
  CiPsd,
  CiRecycle,
  CiRefresh,
  CiRevert,
  CiRevertAlert,
  CiSafari,
  CiSbs,
  CiSbsar,
  CiScale,
  CiScissors,
  CiSend,
  CiSesx,
  CiSettings,
  CiShapes,
  CiShared,
  CiShortArrowRightUp,
  CiSketch,
  CiSkull,
  CiSmod,
  CiSnapshot,
  CiSortAZ,
  CiSortAscendingLetters,
  CiSortAscendingShapes,
  CiSortDescendingLetters,
  CiSortDescendingShapes,
  CiSparkles,
  CiSpp,
  CiSquareArrowRightUp,
  CiSquaresPlus,
  CiSquash,
  CiStall,
  CiStallCog,
  CiStar,
  CiStatusDone,
  CiStatusReady,
  CiStatusRetake,
  CiStatusTodo,
  CiStatusWfa,
  CiStatusWip,
  CiStorefront,
  CiSun,
  CiSvg,
  CiSwitch,
  CiSwitches,
  CiTag,
  CiTexture,
  CiTif,
  CiTranslation,
  CiTrash,
  CiTrashAlt,
  CiTree,
  CiTwoDrives,
  CiTwoPersons,
  CiUnarchive,
  CiUndo,
  CiUndoAlert,
  CiUnpin,
  CiVideoCamera,
  CiWebPlus,
  CiWebsite,
  CiWebsiteLink,
  CiWorkflowArrow,
  CiWorkflowPlus,
  CiXcf,
  CiXstage,
  CiYoutube,
  CiZpr,
  CiZprj
} from '@clustta/icons-vue';

const iconMap = {
  '3b': Ci3b,
  'aep': CiAep,
  'afdesign': CiAfdesign,
  'afphoto': CiAfphoto,
  'afpub': CiAfpub,
  'ai': CiAi,
  'alert': CiAlert,
  'alphabets': CiAlphabets,
  'alphabets-alt': CiAlphabetsAlt,
  'archive': CiArchive,
  'arrow-back-ramp': CiArrowBackRamp,
  'arrow-big-up-lines': CiArrowBigUpLines,
  'arrow-down-on-square-stack': CiArrowDownOnSquareStack,
  'arrow-down-ramp': CiArrowDownRamp,
  'arrow-down-ramp-alert': CiArrowDownRampAlert,
  'arrow-left': CiArrowLeft,
  'arrow-left-ramp': CiArrowLeftRamp,
  'arrow-up-ramp': CiArrowUpRamp,
  'arrow-up-ramp-alert': CiArrowUpRampAlert,
  'arrows-expand': CiArrowsExpand,
  'arrows-sort': CiArrowsSort,
  'bell': CiBell,
  'bezier': CiBezier,
  'blend': CiBlend,
  'bone': CiBone,
  'book': CiBook,
  'bookmark': CiBookmark,
  'boxes': CiBoxes,
  'brain': CiBrain,
  'brand-artstation': CiBrandArtstation,
  'brand-behance': CiBrandBehance,
  'brand-instagram': CiBrandInstagram,
  'brand-linkedin': CiBrandLinkedin,
  'brick': CiBrick,
  'brick-cancel': CiBrickCancel,
  'briefcase': CiBriefcase,
  'briefcase-cog': CiBriefcaseCog,
  'briefcase-plus': CiBriefcasePlus,
  'broom': CiBroom,
  'brush': CiBrush,
  'brush-plus': CiBrushPlus,
  'bug': CiBug,
  'bulb': CiBulb,
  'c-4d': CiC4d,
  'camera': CiCamera,
  'camera-flash': CiCameraFlash,
  'canva': CiCanva,
  'cdr': CiCdr,
  'character-creator': CiCharacterCreator,
  'check': CiCheck,
  'check-circle': CiCheckCircle,
  'checkbox-selected': CiCheckboxSelected,
  'checkbox-selected-active': CiCheckboxSelectedActive,
  'checkbox-unselected': CiCheckboxUnselected,
  'checkpoint-stone': CiCheckpointStone,
  'chevron-double-left': CiChevronDoubleLeft,
  'chevron-down': CiChevronDown,
  'chevron-left': CiChevronLeft,
  'chevron-right': CiChevronRight,
  'chevron-up': CiChevronUp,
  'chproj': CiChproj,
  'chrome': CiChrome,
  'circle-check': CiCircleCheck,
  'circle-check-alert': CiCircleCheckAlert,
  'circle-check-go': CiCircleCheckGo,
  'clapboard': CiClapboard,
  'clickup': CiClickup,
  'clip': CiClip,
  'clipboard': CiClipboard,
  'clock': CiClock,
  'close': CiClose,
  'close-circle': CiCloseCircle,
  'close-window': CiCloseWindow,
  'cloud-cancel': CiCloudCancel,
  'cloud-check': CiCloudCheck,
  'cloud-clock': CiCloudClock,
  'cloud-down': CiCloudDown,
  'cloud-error': CiCloudError,
  'cloud-sync': CiCloudSync,
  'cloud-up': CiCloudUp,
  'clustta': CiClustta,
  'code-bracket': CiCodeBracket,
  'cog': CiCog,
  'collapse-down': CiCollapseDown,
  'collapse-left': CiCollapseLeft,
  'collapse-right': CiCollapseRight,
  'collapse-up': CiCollapseUp,
  'collapse-window': CiCollapseWindow,
  'compass': CiCompass,
  'confirm': CiConfirm,
  'console': CiConsole,
  'copy': CiCopy,
  'cpr': CiCpr,
  'create-snapshot': CiCreateSnapshot,
  'credit-card': CiCreditCard,
  'cube': CiCube,
  'data-download': CiDataDownload,
  'data-upload': CiDataUpload,
  'database-sync': CiDatabaseSync,
  'default': CiDefault,
  'dependency': CiDependency,
  'dependency-graph-2': CiDependencyGraph2,
  'diamond': CiDiamond,
  'digital-binary': CiDigitalBinary,
  'dot-big': CiDotBig,
  'dot-big-alert': CiDotBigAlert,
  'dot-big-danger': CiDotBigDanger,
  'dot-small': CiDotSmall,
  'dot-small-alert': CiDotSmallAlert,
  'dots': CiDots,
  'download': CiDownload,
  'drive': CiDrive,
  'drum': CiDrum,
  'duplicate': CiDuplicate,
  'edit': CiEdit,
  'explorer': CiExplorer,
  'explorer-open': CiExplorerOpen,
  'extension': CiExtension,
  'extension-cancel': CiExtensionCancel,
  'eye': CiEye,
  'eye-cancel': CiEyeCancel,
  'eye-cog': CiEyeCog,
  'face-plus': CiFacePlus,
  'figma': CiFigma,
  'file': CiFile,
  'file-name': CiFileName,
  'file-path': CiFilePath,
  'file-plus': CiFilePlus,
  'file-search': CiFileSearch,
  'file-watch': CiFileWatch,
  'file-zip': CiFileZip,
  'film-reel': CiFilmReel,
  'film-strip': CiFilmStrip,
  'filter': CiFilter,
  'fire': CiFire,
  'firefox': CiFirefox,
  'fla': CiFla,
  'flash': CiFlash,
  'flash-plus': CiFlashPlus,
  'floppy-disk': CiFloppyDisk,
  'flow-chart': CiFlowChart,
  'flp': CiFlp,
  'folder': CiFolder,
  'folder-arrow-in': CiFolderArrowIn,
  'folder-arrow-up-right': CiFolderArrowUpRight,
  'folder-grid': CiFolderGrid,
  'folder-plus': CiFolderPlus,
  'forward-slash': CiForwardSlash,
  'four-squares': CiFourSquares,
  'framer': CiFramer,
  'gamepad': CiGamepad,
  'generic': CiGeneric,
  'google-docs': CiGoogleDocs,
  'google-drive': CiGoogleDrive,
  'help': CiHelp,
  'home': CiHome,
  'iclone': CiIclone,
  'image': CiImage,
  'image-cancel': CiImageCancel,
  'image-plus': CiImagePlus,
  'indd': CiIndd,
  'info': CiInfo,
  'info-triangle': CiInfoTriangle,
  'jigsaw': CiJigsaw,
  'kanban': CiKanban,
  'key': CiKey,
  'kitsu': CiKitsu,
  'kra': CiKra,
  'lamp': CiLamp,
  'launch': CiLaunch,
  'layers': CiLayers,
  'layers-plus': CiLayersPlus,
  'layers-plus-alert': CiLayersPlusAlert,
  'layers-plus-danger': CiLayersPlusDanger,
  'library': CiLibrary,
  'link': CiLink,
  'list': CiList,
  'list-compact': CiListCompact,
  'list-down': CiListDown,
  'loading': CiLoading,
  'lock-closed': CiLockClosed,
  'lock-open': CiLockOpen,
  'login': CiLogin,
  'logout': CiLogout,
  'lrcat': CiLrcat,
  'ma': CiMa,
  'magnifying-glass': CiMagnifyingGlass,
  'mail': CiMail,
  'man-running': CiManRunning,
  'map-pin': CiMapPin,
  'masks': CiMasks,
  'max': CiMax,
  'maximize': CiMaximize,
  'maximize-window': CiMaximizeWindow,
  'megaphone': CiMegaphone,
  'merge': CiMerge,
  'minimize': CiMinimize,
  'minimize-window': CiMinimizeWindow,
  'minus-circle': CiMinusCircle,
  'miro': CiMiro,
  'monitor': CiMonitor,
  'monitor-plus': CiMonitorPlus,
  'moon': CiMoon,
  'music': CiMusic,
  'mystery-ball': CiMysteryBall,
  'new-pin': CiNewPin,
  'node-graph': CiNodeGraph,
  'notion': CiNotion,
  'open-book': CiOpenBook,
  'overflow': CiOverflow,
  'package': CiPackage,
  'palette': CiPalette,
  'paperclip': CiPaperclip,
  'parameters': CiParameters,
  'person': CiPerson,
  'person-circled': CiPersonCircled,
  'person-minus': CiPersonMinus,
  'person-plus': CiPersonPlus,
  'person-search': CiPersonSearch,
  'pin': CiPin,
  'play-pause': CiPlayPause,
  'plug': CiPlug,
  'plus-circle': CiPlusCircle,
  'plus-stone': CiPlusStone,
  'printer': CiPrinter,
  'prproj': CiPrproj,
  'psd': CiPsd,
  'recycle': CiRecycle,
  'refresh': CiRefresh,
  'revert': CiRevert,
  'revert-alert': CiRevertAlert,
  'safari': CiSafari,
  'sbs': CiSbs,
  'sbsar': CiSbsar,
  'scale': CiScale,
  'scissors': CiScissors,
  'send': CiSend,
  'sesx': CiSesx,
  'settings': CiSettings,
  'shapes': CiShapes,
  'shared': CiShared,
  'short-arrow-right-up': CiShortArrowRightUp,
  'sketch': CiSketch,
  'skull': CiSkull,
  'smod': CiSmod,
  'snapshot': CiSnapshot,
  'sort-az': CiSortAZ,
  'sort-ascending-letters': CiSortAscendingLetters,
  'sort-ascending-shapes': CiSortAscendingShapes,
  'sort-descending-letters': CiSortDescendingLetters,
  'sort-descending-shapes': CiSortDescendingShapes,
  'sparkles': CiSparkles,
  'spp': CiSpp,
  'square-arrow-right-up': CiSquareArrowRightUp,
  'squares-plus': CiSquaresPlus,
  'squash': CiSquash,
  'stall': CiStall,
  'stall-cog': CiStallCog,
  'star': CiStar,
  'status-done': CiStatusDone,
  'status-ready': CiStatusReady,
  'status-retake': CiStatusRetake,
  'status-todo': CiStatusTodo,
  'status-wfa': CiStatusWfa,
  'status-wip': CiStatusWip,
  'storefront': CiStorefront,
  'sun': CiSun,
  'svg': CiSvg,
  'switch': CiSwitch,
  'switches': CiSwitches,
  'tag': CiTag,
  'texture': CiTexture,
  'tif': CiTif,
  'translation': CiTranslation,
  'trash': CiTrash,
  'trash-alt': CiTrashAlt,
  'tree': CiTree,
  'two-drives': CiTwoDrives,
  'two-persons': CiTwoPersons,
  'unarchive': CiUnarchive,
  'undo': CiUndo,
  'undo-alert': CiUndoAlert,
  'unpin': CiUnpin,
  'video-camera': CiVideoCamera,
  'web-plus': CiWebPlus,
  'website': CiWebsite,
  'website-link': CiWebsiteLink,
  'workflow-arrow': CiWorkflowArrow,
  'workflow-plus': CiWorkflowPlus,
  'xcf': CiXcf,
  'xstage': CiXstage,
  'youtube': CiYoutube,
  'zpr': CiZpr,
  'zprj': CiZprj,
};

export function resolveIcon(name) {
  if (!name) return null;
  if (typeof name !== 'string') return name;
  const normalized = name.toLowerCase().replace(/[_\s]/g, '-');
  return iconMap[normalized] || null;
}

export default iconMap;
